--- 
title: "Life Contingencies: The Mathematics, Statistics, and Economics of Life Insurance"
author: "An open text authored by the Actuarial Community"
site: bookdown::bookdown_site
output:
  bookdown::gitbook
documentclass: book
bibliography: ["References/LDAReference2020A.bib"]
biblio-style: econPeriod
link-citations: yes
references:
- type: article-journal
github-repo: https://github.com/OpenActTextDev
description: "This is an interactive, online, freely available text.
  -  The online version will contain many interactive objects (quizzes, computer demonstrations, interactive graphs, video, and the like) to promote deeper learning.
  -  A subset of the book will be available in pdf format for low-cost printing.
  -  The online text will be available in multiple languages to promote access to a worldwide audience."
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment=NA, message = FALSE, warning = FALSE, fig.align="center")
knitr::opts_chunk$set(results = "hold")
tutorial::go_interactive(greedy = FALSE)
# options(bookdown.render.file_scope = FALSE)
# knitr::opts_chunk$set(echo = FALSE)
# options(knitr.table.format = function() {if (knitr::is_latex_output()) 'latex' else 'pandoc'})

```

# Preface {-}

<p style="text-align:right;">
*Date: `r format(Sys.Date(), "%d %B %Y")`*</p>

```{r echo = FALSE}
timeDraft <- Sys.time()
```

<!-- `r if (knitr:::is_html_output()) '$\\require{enclose}$'` -->



