<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Modeling Lifetimes | Life Contingencies: The Mathematics, Statistics, and Economics of Life Insurance</title>
  <meta name="description" content="This is an interactive, online, freely available text. - The online version will contain many interactive objects (quizzes, computer demonstrations, interactive graphs, video, and the like) to promote deeper learning. - A subset of the book will be available in pdf format for low-cost printing. - The online text will be available in multiple languages to promote access to a worldwide audience." />
  <meta name="generator" content="bookdown 0.19 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Modeling Lifetimes | Life Contingencies: The Mathematics, Statistics, and Economics of Life Insurance" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is an interactive, online, freely available text. - The online version will contain many interactive objects (quizzes, computer demonstrations, interactive graphs, video, and the like) to promote deeper learning. - A subset of the book will be available in pdf format for low-cost printing. - The online text will be available in multiple languages to promote access to a worldwide audience." />
  <meta name="github-repo" content="https://github.com/OpenActTextDev" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Modeling Lifetimes | Life Contingencies: The Mathematics, Statistics, and Economics of Life Insurance" />
  
  <meta name="twitter:description" content="This is an interactive, online, freely available text. - The online version will contain many interactive objects (quizzes, computer demonstrations, interactive graphs, video, and the like) to promote deeper learning. - A subset of the book will be available in pdf format for low-cost printing. - The online text will be available in multiple languages to promote access to a worldwide audience." />
  

<meta name="author" content="An open text authored by the Actuarial Community" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introduction.html"/>
<link rel="next" href="C-Benefit.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.15/datatables.js"></script>
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.20/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>
<script language="javascript">
function openTab(evt, tabName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(tabName).style.display = "block";
    evt.currentTarget.className += " active";
}

// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
</script>

<script language="javascript">
function toggle(id1,id2) {
	var ele = document.getElementById(id1); var text = document.getElementById(id2);
	if (ele.style.display == "block") {ele.style.display = "none"; text.innerHTML = "Show Solution";}
		else {ele.style.display = "block"; text.innerHTML = "Hide Solution";}}
</script>

<script language="javascript">
function togglecode(id1,id2) {
   var ele = document.getElementById(id1); var text = document.getElementById(id2);
   if (ele.style.display == "block") {ele.style.display = "none"; text.innerHTML = "Show R Code";}
      else {ele.style.display = "block"; text.innerHTML = "Hide R Code";}}
</script>
<script language="javascript">
function toggleEX(id1,id2) {
   var ele = document.getElementById(id1); var text = document.getElementById(id2);
   if (ele.style.display == "block") {ele.style.display = "none"; text.innerHTML = "Show Example";}
      else {ele.style.display = "block"; text.innerHTML = "Hide Example";}}
</script>
<script language="javascript">
function toggleTheory(id1,id2) {
   var ele = document.getElementById(id1); var text = document.getElementById(id2);
   if (ele.style.display == "block") {ele.style.display = "none"; text.innerHTML = "Show Theory";}
      else {ele.style.display = "block"; text.innerHTML = "Hide Theory";}}
</script>

<script language="javascript">
function toggleDet(id1,id2) {
   var ele = document.getElementById(id1); var text = document.getElementById(id2);
   if (ele.style.display == "block") {ele.style.display = "none"; text.innerHTML = "Show Details";}
      else {ele.style.display = "block"; text.innerHTML = "Hide  Details";}}
</script>

<script language="javascript">
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>

<script src=https://cdn.datacamp.com/datacamp-light-latest.min.js></script>

<script src="https://bossanova.uk/jexcel/v4/jexcel.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jexcel/v4/jexcel.css" type="text/css" />
<script src="https://bossanova.uk/jsuites/v3/jsuites.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jsuites/v3/jsuites.css" type="text/css" />


<script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover(); 
});
</script>

<style>
/* Rearrange console label */
.datacamp-exercise ol li, .datacamp-exercise ul li {
  margin-bottom: 0em !important;
}

/* Remove bullet marker */
.datacamp-exercise ol li::before, .datacamp-exercise ul li::before {
  content: '' !important;
}
</style>


<script language="javascript">
var submitAnswer = function() {

  var radios = document.getElementsByName('choice');
  var val= "";
  for (var i = 0, length = radios.length; i < length; i++) {
      if (radios[i].checked) {
         val = radios[i].value; 
         break;
       }
  }
  
  if (val == "" ) {
    alert('please select choice answer');
  } else if ( val == "Correct" ) {
    alert('Answer is correct !');
  } else {
    alert('Answer is wrong');
  }
};
</script>





<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-125587869-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-125587869-1');
</script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Life Contingencies</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contributors"><i class="fa fa-check"></i>Contributors</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#reviewers"><i class="fa fa-check"></i>Reviewers</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#for-our-readers"><i class="fa fa-check"></i>For our Readers</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="modeling-lifetimes.html"><a href="modeling-lifetimes.html"><i class="fa fa-check"></i><b>2</b> Modeling Lifetimes</a><ul>
<li class="chapter" data-level="2.1" data-path="modeling-lifetimes.html"><a href="modeling-lifetimes.html#S:MortData"><i class="fa fa-check"></i><b>2.1</b> Mortality data: Life Expectancies, Deaths, Counts, &amp; Features</a><ul>
<li class="chapter" data-level="2.1.1" data-path="modeling-lifetimes.html"><a href="modeling-lifetimes.html#life-expectancies"><i class="fa fa-check"></i><b>2.1.1</b> Life Expectancies</a></li>
<li class="chapter" data-level="2.1.2" data-path="modeling-lifetimes.html"><a href="modeling-lifetimes.html#population-mortality-counts"><i class="fa fa-check"></i><b>2.1.2</b> Population Mortality Counts</a></li>
<li class="chapter" data-level="2.1.3" data-path="modeling-lifetimes.html"><a href="modeling-lifetimes.html#individual-mortality-data"><i class="fa fa-check"></i><b>2.1.3</b> Individual Mortality Data</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="modeling-lifetimes.html"><a href="modeling-lifetimes.html#S:"><i class="fa fa-check"></i><b>2.2</b> Modeling Death</a><ul>
<li class="chapter" data-level="2.2.1" data-path="modeling-lifetimes.html"><a href="modeling-lifetimes.html#lifetime-random-variable-and-its-distribution"><i class="fa fa-check"></i><b>2.2.1</b> Lifetime random variable and its distribution</a></li>
<li class="chapter" data-level="2.2.2" data-path="modeling-lifetimes.html"><a href="modeling-lifetimes.html#survival-and-mortality-probabilities"><i class="fa fa-check"></i><b>2.2.2</b> Survival and mortality probabilities</a></li>
<li class="chapter" data-level="2.2.3" data-path="modeling-lifetimes.html"><a href="modeling-lifetimes.html#S:LifeExp"><i class="fa fa-check"></i><b>2.2.3</b> Complete expectation of life</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="modeling-lifetimes.html"><a href="modeling-lifetimes.html#S:AnalMortLaws"><i class="fa fa-check"></i><b>2.3</b> Analytical laws of mortality</a></li>
<li class="chapter" data-level="2.4" data-path="modeling-lifetimes.html"><a href="modeling-lifetimes.html#S:LifeTab"><i class="fa fa-check"></i><b>2.4</b> Life tables and their functions</a><ul>
<li class="chapter" data-level="2.4.1" data-path="modeling-lifetimes.html"><a href="modeling-lifetimes.html#S:LifeTabBasic"><i class="fa fa-check"></i><b>2.4.1</b> Life table based on U.S. population data</a></li>
<li class="chapter" data-level="2.4.2" data-path="modeling-lifetimes.html"><a href="modeling-lifetimes.html#S:LifeTabMImpr"><i class="fa fa-check"></i><b>2.4.2</b> Mortality Improvement Modeling</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="modeling-lifetimes.html"><a href="modeling-lifetimes.html#non-parametric-survival-estimation"><i class="fa fa-check"></i><b>2.5</b> Non-parametric survival estimation</a></li>
<li class="chapter" data-level="2.6" data-path="modeling-lifetimes.html"><a href="modeling-lifetimes.html#conditional-models-survival-regression"><i class="fa fa-check"></i><b>2.6</b> Conditional models: Survival regression</a></li>
<li class="chapter" data-level="" data-path="modeling-lifetimes.html"><a href="modeling-lifetimes.html#appendix-2a.-life-table-recursive-calculations"><i class="fa fa-check"></i>Appendix 2A. Life Table: Recursive Calculations</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="C-Benefit.html"><a href="C-Benefit.html"><i class="fa fa-check"></i><b>3</b> Chapter 3 Modeling Life Contingent Benefits</a><ul>
<li class="chapter" data-level="3.1" data-path="C-Benefit.html"><a href="C-Benefit.html#Sec:BenefitCFUnc"><i class="fa fa-check"></i><b>3.1</b> Valuation of cash flows under uncertainty</a></li>
<li class="chapter" data-level="3.2" data-path="C-Benefit.html"><a href="C-Benefit.html#Sec:BenefitActNot"><i class="fa fa-check"></i><b>3.2</b> Life insurance benefits and actuarial notation</a><ul>
<li class="chapter" data-level="3.2.1" data-path="C-Benefit.html"><a href="C-Benefit.html#Sec:BenefitWL"><i class="fa fa-check"></i><b>3.2.1</b> Whole of Life Insurance</a></li>
<li class="chapter" data-level="3.2.2" data-path="C-Benefit.html"><a href="C-Benefit.html#Sec:BenefitTI"><i class="fa fa-check"></i><b>3.2.2</b> Term Insurance</a></li>
<li class="chapter" data-level="3.2.3" data-path="C-Benefit.html"><a href="C-Benefit.html#pure-endowment"><i class="fa fa-check"></i><b>3.2.3</b> Pure Endowment</a></li>
<li class="chapter" data-level="3.2.4" data-path="C-Benefit.html"><a href="C-Benefit.html#endowment-insurance"><i class="fa fa-check"></i><b>3.2.4</b> Endowment Insurance</a></li>
<li class="chapter" data-level="3.2.5" data-path="C-Benefit.html"><a href="C-Benefit.html#life-annuity"><i class="fa fa-check"></i><b>3.2.5</b> Life Annuity</a></li>
<li class="chapter" data-level="3.2.6" data-path="C-Benefit.html"><a href="C-Benefit.html#term-life-annuity"><i class="fa fa-check"></i><b>3.2.6</b> Term Life Annuity</a></li>
<li class="chapter" data-level="3.2.7" data-path="C-Benefit.html"><a href="C-Benefit.html#deferred-life-annuity"><i class="fa fa-check"></i><b>3.2.7</b> Deferred Life Annuity</a></li>
<li class="chapter" data-level="3.2.8" data-path="C-Benefit.html"><a href="C-Benefit.html#guaranteed-life-annuity"><i class="fa fa-check"></i><b>3.2.8</b> Guaranteed Life Annuity</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="C-Benefit.html"><a href="C-Benefit.html#Sec:BenefitLT"><i class="fa fa-check"></i><b>3.3</b> Bringing actuarial notation to the Life Table</a></li>
<li class="chapter" data-level="3.4" data-path="C-Benefit.html"><a href="C-Benefit.html#Sec:BenefitCS"><i class="fa fa-check"></i><b>3.4</b> Case Study: Valuing the benefits of a portfolio of term insurance policies</a><ul>
<li class="chapter" data-level="3.4.1" data-path="C-Benefit.html"><a href="C-Benefit.html#Sec:BenefitCSInd"><i class="fa fa-check"></i><b>3.4.1</b> An individual policy</a></li>
<li class="chapter" data-level="3.4.2" data-path="C-Benefit.html"><a href="C-Benefit.html#Sec:BenefitCSPort"><i class="fa fa-check"></i><b>3.4.2</b> A portfolio of policies</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="C-Benefit.html"><a href="C-Benefit.html#the-impact-of-self-selection"><i class="fa fa-check"></i><b>3.5</b> The impact of self selection</a></li>
<li class="chapter" data-level="3.6" data-path="C-Benefit.html"><a href="C-Benefit.html#modelling-contingent-cash-flows-more-frequently-than-annually"><i class="fa fa-check"></i><b>3.6</b> Modelling contingent cash flows more frequently than annually</a></li>
<li class="chapter" data-level="3.7" data-path="C-Benefit.html"><a href="C-Benefit.html#modelling-contingent-cash-flows-in-continuous-time"><i class="fa fa-check"></i><b>3.7</b> Modelling contingent cash flows in continuous time</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="chapter-3-examples-present-values.html"><a href="chapter-3-examples-present-values.html"><i class="fa fa-check"></i>Chapter 3 Examples – Present Values</a><ul>
<li class="chapter" data-level="" data-path="chapter-3-examples-present-values.html"><a href="chapter-3-examples-present-values.html#examples-valuation-of-cash-flows-under-uncertainty"><i class="fa fa-check"></i>Examples – Valuation of cash flows under uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="C-NotationConventionLC.html"><a href="C-NotationConventionLC.html"><i class="fa fa-check"></i><b>4</b> Appendix: Conventions for Notation</a><ul>
<li class="chapter" data-level="4.1" data-path="C-NotationConventionLC.html"><a href="C-NotationConventionLC.html#S:NC:General"><i class="fa fa-check"></i><b>4.1</b> General Conventions</a></li>
<li class="chapter" data-level="4.2" data-path="C-NotationConventionLC.html"><a href="C-NotationConventionLC.html#S:NC:Abbreviations"><i class="fa fa-check"></i><b>4.2</b> Abbreviations</a></li>
<li class="chapter" data-level="4.3" data-path="C-NotationConventionLC.html"><a href="C-NotationConventionLC.html#S:NC:StatSymbols"><i class="fa fa-check"></i><b>4.3</b> Common Statistical Symbols and Operators</a></li>
<li class="chapter" data-level="4.4" data-path="C-NotationConventionLC.html"><a href="C-NotationConventionLC.html#S:NC:Symbols"><i class="fa fa-check"></i><b>4.4</b> Common Mathematical Symbols and Functions</a></li>
<li class="chapter" data-level="4.5" data-path="C-NotationConventionLC.html"><a href="C-NotationConventionLC.html#S:NC:ActSymbols"><i class="fa fa-check"></i><b>4.5</b> Actuarial Notation</a><ul>
<li class="chapter" data-level="4.5.1" data-path="C-NotationConventionLC.html"><a href="C-NotationConventionLC.html#life-table-notation"><i class="fa fa-check"></i><b>4.5.1</b> Life Table Notation</a></li>
<li class="chapter" data-level="4.5.2" data-path="C-NotationConventionLC.html"><a href="C-NotationConventionLC.html#annuity-certain-and-life-annuity-notation"><i class="fa fa-check"></i><b>4.5.2</b> Annuity Certain and Life Annuity Notation</a></li>
<li class="chapter" data-level="4.5.3" data-path="C-NotationConventionLC.html"><a href="C-NotationConventionLC.html#life-insurance-notation"><i class="fa fa-check"></i><b>4.5.3</b> Life Insurance Notation</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="C-NotationConventionLC.html"><a href="C-NotationConventionLC.html#C:NotConv:Halo"><i class="fa fa-check"></i><b>4.6</b> Halo System</a></li>
<li class="chapter" data-level="4.7" data-path="C-NotationConventionLC.html"><a href="C-NotationConventionLC.html#further-readings"><i class="fa fa-check"></i><b>4.7</b> Further Readings</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bibliography.html"><a href="bibliography.html"><i class="fa fa-check"></i>Bibliography</a></li>
<li class="divider"></li>
<li><a href="https://github.com/OpenActTextDev/LifeCon" target="blank">Life Contingencies on GitHub</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Life Contingencies: The Mathematics, Statistics, and Economics of Life Insurance</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modeling-lifetimes" class="section level1">
<h1><span class="header-section-number">Chapter 2</span> Modeling Lifetimes</h1>
<p>The analysis of life-contingent exposures such as insurer’s liability when selling a life insurance contract or a pension fund’s obligations when offering a new pension scheme starts with modeling individual <em>lifetime</em> and <em>death</em>. These models, in turn, have to be calibrated in the context of relevant (mortality) data.</p>
<p>Therefore, in this chapter, we first present different types of data that describe the mortality and lifetimes of certain population. We deliberately introduce the data in Section <a href="modeling-lifetimes.html#S:MortData">2.1</a> without assuming prior knowledge of life-contingent modeling, and aim to develop an intuitive understanding of some of the associated challenges.</p>
<p>We then introduce the conventional framework for modeling lifetimes, particularly by introducing the concept of a future lifetime variable <span class="math inline">\(T_{\bf x}\)</span> and its properties, and we then explore various approaches of specifying and estimating its distribution. Here, we discuss the traditional actuarial models for lifetimes such as analytical mortality laws and life tables, but we also introduce conditional predictive models that characterize the lifetime distribution based on a set of covariates or <em>features</em>.</p>
<div id="S:MortData" class="section level2">
<h2><span class="header-section-number">2.1</span> Mortality data: Life Expectancies, Deaths, Counts, &amp; Features</h2>
<div id="life-expectancies" class="section level3">
<h3><span class="header-section-number">2.1.1</span> Life Expectancies</h3>
<p>Perhaps the most relevant question to any individual when it comes to their future lifetime is: how long am I expected to live? Government agencies around the world publish vital statistics such as the <em>life expectancies</em> for their population, which are typically separated by age and gender – and potentially other attributes such as race.</p>
<p>The file <code>CDCLifeExp.csv</code> is provided with the supplemental information of this text and includes an excerpt of the U.S. <a href="https://www.cdc.gov/nchs/data/nvsr/nvsr68/nvsr68_07-508.pdf">national vital statistics</a> that provides “Expectation of life, by age, race, […] and sex: United States, 2017” in Table <a href="modeling-lifetimes.html#tab:MortChapCDC">2.1</a>.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" title="1"><span class="kw">library</span>(knitr)</a>
<a class="sourceLine" id="cb2-2" title="2">us_les &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;Data/CDCLifeExp.csv&quot;</span>)</a>
<a class="sourceLine" id="cb2-3" title="3"><span class="kw">kable</span>(us_les, <span class="dt">caption=</span><span class="st">&quot;Life Expectancies From U.S. Vital Statistics&quot;</span>)</a></code></pre></div>
<table>
<caption><span id="tab:MortChapCDC">Table 2.1: </span>Life Expectancies From U.S. Vital Statistics</caption>
<thead>
<tr class="header">
<th align="right">Age</th>
<th align="right">Total</th>
<th align="right">Male</th>
<th align="right">Female</th>
<th align="right">Hispanic..Total</th>
<th align="right">Hispanic..Male</th>
<th align="right">Hispanic..Female</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="right">78.6</td>
<td align="right">76.1</td>
<td align="right">81.1</td>
<td align="right">81.8</td>
<td align="right">79.1</td>
<td align="right">84.3</td>
</tr>
<tr class="even">
<td align="right">20</td>
<td align="right">59.4</td>
<td align="right">57.0</td>
<td align="right">61.8</td>
<td align="right">62.5</td>
<td align="right">59.9</td>
<td align="right">64.9</td>
</tr>
<tr class="odd">
<td align="right">40</td>
<td align="right">40.7</td>
<td align="right">38.7</td>
<td align="right">42.6</td>
<td align="right">43.5</td>
<td align="right">41.2</td>
<td align="right">45.5</td>
</tr>
<tr class="even">
<td align="right">60</td>
<td align="right">23.3</td>
<td align="right">21.7</td>
<td align="right">24.7</td>
<td align="right">25.5</td>
<td align="right">23.6</td>
<td align="right">27.0</td>
</tr>
<tr class="odd">
<td align="right">80</td>
<td align="right">9.2</td>
<td align="right">8.4</td>
<td align="right">9.8</td>
<td align="right">10.5</td>
<td align="right">9.4</td>
<td align="right">11.1</td>
</tr>
</tbody>
</table>
<p>The excerpt provides the life expectancy for ages 0 (newborn), 20, 40, 60, and 80 observed within a population, for males and females with separate figures for the hispanic subpopulation. There are a few immediate observations.</p>
<p>First, females generally seem to have a longer life expectancy than males, whereas the aggregate “Total” life expectancy is in between the two figures. This is intuitive as the aggregate population is (largely) made up of male and female individuals, so that the “Total” life expectancy is a weighted average of the gender-specific life expectancies, relative to the composition of the population.</p>
<p>Second, life expectancy is decreasing in age, which again is intuitive. It may be somewhat less obvious that the differences in life expectancies are less than the differences in age; subtracting the lines in the Table <a href="modeling-lifetimes.html#tab:MortChapCDC">2.1</a> gives that</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1"><span class="kw">kable</span>(us_les[<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>,]<span class="op">-</span>us_les[<span class="dv">2</span><span class="op">:</span><span class="dv">5</span>,])</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">Age</th>
<th align="right">Total</th>
<th align="right">Male</th>
<th align="right">Female</th>
<th align="right">Hispanic..Total</th>
<th align="right">Hispanic..Male</th>
<th align="right">Hispanic..Female</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">-20</td>
<td align="right">19.2</td>
<td align="right">19.1</td>
<td align="right">19.3</td>
<td align="right">19.3</td>
<td align="right">19.2</td>
<td align="right">19.4</td>
</tr>
<tr class="even">
<td align="right">-20</td>
<td align="right">18.7</td>
<td align="right">18.3</td>
<td align="right">19.2</td>
<td align="right">19.0</td>
<td align="right">18.7</td>
<td align="right">19.4</td>
</tr>
<tr class="odd">
<td align="right">-20</td>
<td align="right">17.4</td>
<td align="right">17.0</td>
<td align="right">17.9</td>
<td align="right">18.0</td>
<td align="right">17.6</td>
<td align="right">18.5</td>
</tr>
<tr class="even">
<td align="right">-20</td>
<td align="right">14.1</td>
<td align="right">13.3</td>
<td align="right">14.9</td>
<td align="right">15.0</td>
<td align="right">14.2</td>
<td align="right">15.9</td>
</tr>
</tbody>
</table>
<p>Hence, while a 40-year old male is twenty years older than a 20-year old male, the 20-year old’s life expectancy is 18.3 years higher. The difference of 1.7 years is due to the possibility of the 20-year old not surviving up to age 40. This effect is clearly more pronounced when comparing the 40-year old with a 60-year old.</p>
<p>Third, the life expectancies for the hispanic subpopulation exceed those of the total population, which suggests that other subpopulations must exhibit a lower life expectancy. There are many questions of potential reasons for this difference, although these fall more in the demographic or even sociological realm.</p>
<p>From an actuarial perspective, a relevant question may be how we could model the mortality data. In other words, is there a simple parametric model that may describe the progression of life expectancy across ages, at least in the context of one particular population? We will return to this question in the context of our mortality models, particularly in Section <a href="modeling-lifetimes.html#S:AnalMortLaws">2.3</a>.</p>
<p>As an early caveat to the question raised at the beginning of this section, it is not necessarily accurate to take these figures as estimates of a given individual’s future lifetime or even its expectation. This is the case since the <em>life expectancy</em> is usually generated based on recent mortality <em>experience</em> rather than <em>forecasts</em>. As we will discuss in Section <a href="modeling-lifetimes.html#S:LifeTab">2.4</a>, this is the difference between the so-called <em>period</em> and <em>cohort</em> life expectancies.</p>
</div>
<div id="population-mortality-counts" class="section level3">
<h3><span class="header-section-number">2.1.2</span> Population Mortality Counts</h3>
<p>We now bring into consideration of the population <em>mortality experience</em> that had been observed over time, which is available at the <a href="https://www.mortality.org">Human Mortality Database (HMD)</a> for a wide range of countries. The available data include <em>Exposures</em> by age, sex, and calender year period, i.e. how many people people of a given age and sex lived in the country’s population during a given period of time, and corresponding <em>Deaths</em>, i.e. how many of these individuals had died.</p>
<p>In the supplemental information to this text, we provide exposures and deaths for the U.S. population, downloaded from the HMD as <code>HMD_Expo.csv</code> and <code>HMD_Deaths.csv</code>. We use the data over five year intervals starting at 1935 until 2015. Let us take a look at the exposures</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" title="1">us_exp &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;Data/HMD_Expo.csv&quot;</span>)</a>
<a class="sourceLine" id="cb4-2" title="2"><span class="kw">kable</span>(<span class="kw">head</span>(us_exp), <span class="dt">align =</span> <span class="st">&quot;cccrrr&quot;</span>, <span class="dt">digits =</span> <span class="dv">2</span>, <span class="dt">format.args =</span> <span class="kw">list</span>(<span class="dt">big.mark =</span> <span class="st">&quot;,&quot;</span>))</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="center">Year_start</th>
<th align="center">Year_end</th>
<th align="center">Age</th>
<th align="right">Female</th>
<th align="right">Male</th>
<th align="right">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1,935</td>
<td align="center">1,939</td>
<td align="center">0</td>
<td align="right">4,869,267</td>
<td align="right">5,057,569</td>
<td align="right">9,926,836</td>
</tr>
<tr class="even">
<td align="center">1,935</td>
<td align="center">1,939</td>
<td align="center">1</td>
<td align="right">4,802,597</td>
<td align="right">4,936,238</td>
<td align="right">9,738,835</td>
</tr>
<tr class="odd">
<td align="center">1,935</td>
<td align="center">1,939</td>
<td align="center">2</td>
<td align="right">5,119,574</td>
<td align="right">5,244,634</td>
<td align="right">10,364,208</td>
</tr>
<tr class="even">
<td align="center">1,935</td>
<td align="center">1,939</td>
<td align="center">3</td>
<td align="right">5,159,494</td>
<td align="right">5,287,402</td>
<td align="right">10,446,896</td>
</tr>
<tr class="odd">
<td align="center">1,935</td>
<td align="center">1,939</td>
<td align="center">4</td>
<td align="right">5,189,350</td>
<td align="right">5,307,754</td>
<td align="right">10,497,104</td>
</tr>
<tr class="even">
<td align="center">1,935</td>
<td align="center">1,939</td>
<td align="center">5</td>
<td align="right">5,359,159</td>
<td align="right">5,531,967</td>
<td align="right">10,891,126</td>
</tr>
</tbody>
</table>
<p>and deaths</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1">us_deaths &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;Data/HMD_Deaths.csv&quot;</span>)</a>
<a class="sourceLine" id="cb5-2" title="2"><span class="kw">kable</span>(<span class="kw">head</span>(us_deaths), <span class="dt">align =</span> <span class="st">&quot;cccrrr&quot;</span>, <span class="dt">digits =</span> <span class="dv">2</span>, <span class="dt">format.args =</span> <span class="kw">list</span>(<span class="dt">big.mark =</span> <span class="st">&quot;,&quot;</span>))</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="center">Year_start</th>
<th align="center">Year_end</th>
<th align="center">Age</th>
<th align="right">Female</th>
<th align="right">Male</th>
<th align="right">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1,935</td>
<td align="center">1,939</td>
<td align="center">0</td>
<td align="right">253,145.89</td>
<td align="right">335,492.00</td>
<td align="right">588,637.89</td>
</tr>
<tr class="even">
<td align="center">1,935</td>
<td align="center">1,939</td>
<td align="center">1</td>
<td align="right">36,010.02</td>
<td align="right">42,169.20</td>
<td align="right">78,179.22</td>
</tr>
<tr class="odd">
<td align="center">1,935</td>
<td align="center">1,939</td>
<td align="center">2</td>
<td align="right">17,718.83</td>
<td align="right">21,208.22</td>
<td align="right">38,927.05</td>
</tr>
<tr class="even">
<td align="center">1,935</td>
<td align="center">1,939</td>
<td align="center">3</td>
<td align="right">12,450.36</td>
<td align="right">14,852.17</td>
<td align="right">27,302.53</td>
</tr>
<tr class="odd">
<td align="center">1,935</td>
<td align="center">1,939</td>
<td align="center">4</td>
<td align="right">10,154.85</td>
<td align="right">11,771.25</td>
<td align="right">21,926.10</td>
</tr>
<tr class="even">
<td align="center">1,935</td>
<td align="center">1,939</td>
<td align="center">5</td>
<td align="right">8,678.43</td>
<td align="right">10,339.57</td>
<td align="right">19,018.00</td>
</tr>
</tbody>
</table>
<p>Let us be more specific and plot the exposures and deaths for a 70 year old U.S. females over time, which is given in Figure @ref(fig:70ChapHMDU.S.Figs)</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" title="1"><span class="kw">options</span>(<span class="dt">digits =</span> <span class="dv">9</span>)</a>
<a class="sourceLine" id="cb6-2" title="2"><span class="kw">options</span>(<span class="dt">scipen =</span> <span class="dv">9</span>)</a>
<a class="sourceLine" id="cb6-3" title="3"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb6-4" title="4"><span class="kw">plot</span>(us_exp[us_exp<span class="op">$</span>Age <span class="op">==</span><span class="st"> </span><span class="dv">70</span>,<span class="dv">2</span>], us_exp[us_exp<span class="op">$</span>Age <span class="op">==</span><span class="st"> </span><span class="dv">70</span>,<span class="dv">4</span>]<span class="op">/</span><span class="dv">1000</span>, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;green&quot;</span>, <span class="dt">main=</span><span class="st">&quot;Exposures&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;year&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;count&quot;</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="kw">max</span>(us_exp[us_exp<span class="op">$</span>Age <span class="op">==</span><span class="st"> </span><span class="dv">70</span>,<span class="dv">4</span>])<span class="op">/</span><span class="dv">1000</span>))</a>
<a class="sourceLine" id="cb6-5" title="5"><span class="kw">plot</span>(us_deaths[us_deaths<span class="op">$</span>Age <span class="op">==</span><span class="st"> </span><span class="dv">70</span>,<span class="dv">2</span>], us_deaths[us_deaths<span class="op">$</span>Age <span class="op">==</span><span class="st"> </span><span class="dv">70</span>,<span class="dv">4</span>]<span class="op">/</span><span class="dv">1000</span>, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">main=</span><span class="st">&quot;Deaths&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;year&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;count&quot;</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="kw">max</span>(us_deaths[us_deaths<span class="op">$</span>Age <span class="op">==</span><span class="st"> </span><span class="dv">70</span>,<span class="dv">4</span>])<span class="op">/</span><span class="dv">1000</span>))</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:70ChapHMDUSFigs"></span>
<img src="LifeCon_files/figure-html/70ChapHMDUSFigs-1.png" alt="Exposures and Deaths (in thousands) for Females age 70 from the HMD U.S." width="768" />
<p class="caption">
Figure 2.1: Exposures and Deaths (in thousands) for Females age 70 from the HMD U.S.
</p>
</div>
<p>The stark increase in exposures is due to two effects; on one hand, the U.S. population had been growing substantially since 1935, and on the other hand, individuals had been showing an enhanced life expectancy over the time. As a consequence, the number of 70 year old U.S. females had increased from less than two million to more than six million. In contrast, the number of deaths had been more steady; While with an increasing number of exposures the number of deaths have increased, the chance of dying for a 70 year old had been decreasing. The latter becomes more evident by plotting the ratio of deaths and exposures as in Figure <a href="modeling-lifetimes.html#fig:70DRChapHMDUSFigs">2.2</a></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</a>
<a class="sourceLine" id="cb7-2" title="2">minlim &lt;-<span class="st"> </span><span class="kw">min</span>(us_deaths[us_deaths<span class="op">$</span>Age <span class="op">==</span><span class="st"> </span><span class="dv">70</span>,<span class="dv">4</span>]<span class="op">/</span>us_exp[us_exp<span class="op">$</span>Age <span class="op">==</span><span class="st"> </span><span class="dv">70</span>,<span class="dv">4</span>])</a>
<a class="sourceLine" id="cb7-3" title="3">maxlim &lt;-<span class="st"> </span><span class="kw">max</span>(us_deaths[us_deaths<span class="op">$</span>Age <span class="op">==</span><span class="st"> </span><span class="dv">70</span>,<span class="dv">4</span>]<span class="op">/</span>us_exp[us_exp<span class="op">$</span>Age <span class="op">==</span><span class="st"> </span><span class="dv">70</span>,<span class="dv">4</span>])</a>
<a class="sourceLine" id="cb7-4" title="4"><span class="kw">plot</span>(us_deaths[us_deaths<span class="op">$</span>Age <span class="op">==</span><span class="st"> </span><span class="dv">70</span>,<span class="dv">2</span>],us_deaths[us_deaths<span class="op">$</span>Age <span class="op">==</span><span class="st"> </span><span class="dv">70</span>,<span class="dv">4</span>]<span class="op">/</span>us_exp[us_exp<span class="op">$</span>Age <span class="op">==</span><span class="st"> </span><span class="dv">70</span>,<span class="dv">4</span>],<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">main=</span><span class="st">&quot;Deaths/Exposures&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;year&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;rate&quot;</span>,<span class="dt">ylim =</span> <span class="kw">c</span>(minlim,maxlim))</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:70DRChapHMDUSFigs"></span>
<img src="LifeCon_files/figure-html/70DRChapHMDUSFigs-1.png" alt="Death rates for Females age 70 from the HMD U.S." width="576" />
<p class="caption">
Figure 2.2: Death rates for Females age 70 from the HMD U.S.
</p>
</div>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" title="1"><span class="kw">rm</span>(minlim, maxlim)</a></code></pre></div>
<p>Note that the chance of deceasing for a 70 year old female was more than 4% around 1940, but it had decreased over the time to a level lower than 2%. As we will see in Section <a href="modeling-lifetimes.html#S:LifeTab">2.4</a>, the ratio of deaths and exposures is closely related to <em>death rates</em>.</p>
<p>Alternatively, we can focus on a specific period – say the most recent five years in our data, i.e. 2010-2014 – and plot the deaths over exposures across ages as in Figure <a href="modeling-lifetimes.html#fig:AllDRChapHMDUSFigs">2.3</a></p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1">us_mx_fem_<span class="dv">2014</span> &lt;-<span class="st"> </span>us_deaths[us_deaths<span class="op">$</span>Year_start <span class="op">==</span><span class="st"> </span><span class="dv">2010</span>,<span class="dv">4</span>]<span class="op">/</span>us_exp[us_exp<span class="op">$</span>Year_start <span class="op">==</span><span class="st"> </span><span class="dv">2010</span>,<span class="dv">4</span>]</a>
<a class="sourceLine" id="cb9-2" title="2">us_mx_mal_<span class="dv">2014</span> &lt;-<span class="st"> </span>us_deaths[us_deaths<span class="op">$</span>Year_start <span class="op">==</span><span class="st"> </span><span class="dv">2010</span>,<span class="dv">5</span>]<span class="op">/</span>us_exp[us_exp<span class="op">$</span>Year_start <span class="op">==</span><span class="st"> </span><span class="dv">2010</span>,<span class="dv">5</span>]</a>
<a class="sourceLine" id="cb9-3" title="3"><span class="kw">plot</span>(us_mx_fem_<span class="dv">2014</span>,<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">main=</span><span class="st">&quot;Deaths/Exposures&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;year&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;rate&quot;</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="kw">min</span>(us_mx_fem_<span class="dv">2014</span>),<span class="kw">max</span>(us_mx_fem_<span class="dv">2014</span>)))</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:AllDRChapHMDUSFigs"></span>
<img src="LifeCon_files/figure-html/AllDRChapHMDUSFigs-1.png" alt="Death rates for Females across ages for 2010-2014 from the HMD U.S." width="576" />
<p class="caption">
Figure 2.3: Death rates for Females across ages for 2010-2014 from the HMD U.S.
</p>
</div>
<p>Not very surprisingly, the death rate increases fairly regularly with respect to age and its growth looks exponential. This observation is the foundation for the most famous and common analytic mortality model that is detailed in Section <a href="modeling-lifetimes.html#S:AnalMortLaws">2.3</a> known as the <em>Gompertz law</em>. It should be noted that the death rates at higher ages, specifically from 106 to 110, are shown a larger variability that could be explained by the fact very small subpopulations of high ages are observed and the estimates are more uncertain than those at lower ages.</p>
</div>
<div id="individual-mortality-data" class="section level3">
<h3><span class="header-section-number">2.1.3</span> Individual Mortality Data</h3>
<p>While mortality <em>counts</em> are a common way to organize mortality data across a large population, which had been our emphasis in the previous section, the individual survival time data provide valuable pieces of information. Indeed, the data available to an insurance company typically consists of records of individuals. The company records individual details for each insured person from when they purchased the contract; these include personal characteristics such as sex, age, date-of-birth, etc., but also medical records and other <em>underwriting information</em>. In addition, the company knows whether or not the person had died at the current time—and if so, the time of death.</p>
<p>This latter aspect is common for <em>survival</em> or <em>event history data</em>. For each observation <span class="math inline">\(i\)</span>, a number of covariates or <em>features</em> <span class="math inline">\(x_i\)</span>, as well as the <em>event time</em> <span class="math inline">\(T_i\)</span> <em>if</em> the event has already happened. Otherwise, we only know that by the current <em>cutoff</em> time, the event has not happened yet. In the context of <em>survival analysis</em>, which is the branch of statistics that deals with <em>survival</em> or <em>event data</em>, this is known as <em>(right) censoring</em>, i.e. the data are (right-)censored.</p>
<p>Data protection policies are omnipresent and insurance companies are not any different with respect to the policyholder data. On one hand, there are regulatory data protection that disallow disclosure of personal identifiable pieces of information. On the other hand, data are a key resource to a life insurer and sharing this valuable piece of information creates a competition disadvantage by revealing important information to the company’s competitive position. Therefore, rather than relying on real survival data, we consider a synthetic dataset consisting of a hypothetical portfolio of policyholders.</p>
<p>In the supplemental information to this text, we provide survival information for a hypothetical insurance company in <code>SyntheticInsurerData.csv</code>. The company has sold whole life insurance policies for since 1955. Policyholders have to go through an underwriting examination, and in addition to policyholders’ age, sex (0 for female, 1 for male), smoking status (0 for non-smoker, 1 for smoker), and the month of sale, the company records the applicants body-mass index (BMI) and the systolic blood pressure at the time of underwriting. Finally, for those policyholder with a claim, i.e., for the policyholders that have died, the company records the time of death (relative to the month of underwriting). The data is organized in the order of sales, so that the oldest entries are at the top of the data and the newest entries are at the bottom:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" title="1"><span class="kw">library</span>(data.table)</a>
<a class="sourceLine" id="cb10-2" title="2">ins_data &lt;-<span class="st"> </span><span class="kw">fread</span>(<span class="st">&quot;Data/SyntheticInsurerData.csv&quot;</span>,<span class="dt">data.table=</span><span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb10-3" title="3"><span class="kw">kable</span>(<span class="kw">head</span>(ins_data), <span class="dt">align =</span> <span class="st">&quot;ccccrrrr&quot;</span>)</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="center">Month_of_Sale</th>
<th align="center">Age</th>
<th align="center">Sex</th>
<th align="center">Smoking</th>
<th align="right">BMI</th>
<th align="right">BloodPressure</th>
<th align="right">Claim</th>
<th align="right">Time_of_death</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">27</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="right">25.8</td>
<td align="right">117</td>
<td align="right">YES</td>
<td align="right">61.11</td>
</tr>
<tr class="even">
<td align="center">1</td>
<td align="center">62</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="right">30.9</td>
<td align="right">147</td>
<td align="right">YES</td>
<td align="right">17.42</td>
</tr>
<tr class="odd">
<td align="center">1</td>
<td align="center">52</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="right">26.7</td>
<td align="right">130</td>
<td align="right">YES</td>
<td align="right">27.96</td>
</tr>
<tr class="even">
<td align="center">1</td>
<td align="center">40</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="right">27.5</td>
<td align="right">109</td>
<td align="right">YES</td>
<td align="right">52.33</td>
</tr>
<tr class="odd">
<td align="center">1</td>
<td align="center">24</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="right">21.5</td>
<td align="right">96</td>
<td align="right">YES</td>
<td align="right">40.84</td>
</tr>
<tr class="even">
<td align="center">1</td>
<td align="center">31</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="right">20.3</td>
<td align="right">119</td>
<td align="right">YES</td>
<td align="right">53.99</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1"><span class="co">#displaying the very end of the table similar to the very top of the table requires a few more steps</span></a>
<a class="sourceLine" id="cb11-2" title="2">tmp_tail_ins_data &lt;-<span class="st"> </span><span class="kw">tail</span>(ins_data); <span class="kw">rownames</span>(tmp_tail_ins_data) &lt;-<span class="st"> </span><span class="ot">NULL</span></a>
<a class="sourceLine" id="cb11-3" title="3"><span class="kw">kable</span>(tmp_tail_ins_data, <span class="dt">align =</span> <span class="st">&quot;ccccrrrr&quot;</span>)</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="center">Month_of_Sale</th>
<th align="center">Age</th>
<th align="center">Sex</th>
<th align="center">Smoking</th>
<th align="right">BMI</th>
<th align="right">BloodPressure</th>
<th align="right">Claim</th>
<th align="right">Time_of_death</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">780</td>
<td align="center">28</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="right">24.2</td>
<td align="right">97</td>
<td align="right">NO</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="center">780</td>
<td align="center">53</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="right">19.9</td>
<td align="right">138</td>
<td align="right">NO</td>
<td align="right">NA</td>
</tr>
<tr class="odd">
<td align="center">780</td>
<td align="center">32</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="right">22.2</td>
<td align="right">102</td>
<td align="right">NO</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="center">780</td>
<td align="center">48</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="right">18.6</td>
<td align="right">117</td>
<td align="right">NO</td>
<td align="right">NA</td>
</tr>
<tr class="odd">
<td align="center">780</td>
<td align="center">36</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="right">17.5</td>
<td align="right">114</td>
<td align="right">NO</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="center">780</td>
<td align="center">49</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="right">29.7</td>
<td align="right">130</td>
<td align="right">NO</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
<p>Evidently, most of the policies sold in the first months—back in 1955—have matured, and most recent underwritten policyholder are still alive. Let us further investigate the mortality dataframe and we start by summarizing the attributes of our data:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" title="1"><span class="kw">suppressWarnings</span>(<span class="kw">library</span>(psych))</a>
<a class="sourceLine" id="cb12-2" title="2">tmp_describe_ins_data &lt;-<span class="st"> </span>psych<span class="op">::</span><span class="kw">describe</span>(ins_data)</a>
<a class="sourceLine" id="cb12-3" title="3"><span class="kw">kable</span>(tmp_describe_ins_data, <span class="dt">digits =</span> <span class="dv">2</span>, <span class="dt">format.args =</span> <span class="kw">list</span>(<span class="dt">big.mark =</span> <span class="st">&quot;,&quot;</span>))</a></code></pre></div>
<table style="width:100%;">
<colgroup>
<col width="13%" />
<col width="4%" />
<col width="7%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
<col width="7%" />
<col width="6%" />
<col width="5%" />
<col width="6%" />
<col width="6%" />
<col width="5%" />
<col width="8%" />
<col width="4%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">vars</th>
<th align="right">n</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">median</th>
<th align="right">trimmed</th>
<th align="right">mad</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">range</th>
<th align="right">skew</th>
<th align="right">kurtosis</th>
<th align="right">se</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Month_of_Sale</td>
<td align="right">1</td>
<td align="right">160,781</td>
<td align="right">394.58</td>
<td align="right">216.72</td>
<td align="right">382.00</td>
<td align="right">393.08</td>
<td align="right">277.25</td>
<td align="right">1.00</td>
<td align="right">780.00</td>
<td align="right">779.00</td>
<td align="right">0.08</td>
<td align="right">-1.17</td>
<td align="right">0.54</td>
</tr>
<tr class="even">
<td align="left">Age</td>
<td align="right">2</td>
<td align="right">160,781</td>
<td align="right">39.99</td>
<td align="right">11.63</td>
<td align="right">39.00</td>
<td align="right">39.64</td>
<td align="right">11.86</td>
<td align="right">19.00</td>
<td align="right">65.00</td>
<td align="right">46.00</td>
<td align="right">0.22</td>
<td align="right">-0.73</td>
<td align="right">0.03</td>
</tr>
<tr class="odd">
<td align="left">Sex</td>
<td align="right">3</td>
<td align="right">160,781</td>
<td align="right">0.70</td>
<td align="right">0.46</td>
<td align="right">1.00</td>
<td align="right">0.75</td>
<td align="right">0.00</td>
<td align="right">0.00</td>
<td align="right">1.00</td>
<td align="right">1.00</td>
<td align="right">-0.88</td>
<td align="right">-1.23</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">Smoking</td>
<td align="right">4</td>
<td align="right">160,781</td>
<td align="right">0.30</td>
<td align="right">0.46</td>
<td align="right">0.00</td>
<td align="right">0.25</td>
<td align="right">0.00</td>
<td align="right">0.00</td>
<td align="right">1.00</td>
<td align="right">1.00</td>
<td align="right">0.88</td>
<td align="right">-1.23</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">BMI</td>
<td align="right">5</td>
<td align="right">160,781</td>
<td align="right">22.77</td>
<td align="right">4.52</td>
<td align="right">21.70</td>
<td align="right">22.19</td>
<td align="right">3.85</td>
<td align="right">16.10</td>
<td align="right">65.50</td>
<td align="right">49.40</td>
<td align="right">1.42</td>
<td align="right">3.00</td>
<td align="right">0.01</td>
</tr>
<tr class="even">
<td align="left">BloodPressure</td>
<td align="right">6</td>
<td align="right">160,781</td>
<td align="right">114.75</td>
<td align="right">15.75</td>
<td align="right">114.00</td>
<td align="right">114.37</td>
<td align="right">16.31</td>
<td align="right">53.00</td>
<td align="right">199.00</td>
<td align="right">146.00</td>
<td align="right">0.25</td>
<td align="right">0.09</td>
<td align="right">0.04</td>
</tr>
<tr class="odd">
<td align="left">Claim*</td>
<td align="right">7</td>
<td align="right">160,781</td>
<td align="right">1.36</td>
<td align="right">0.48</td>
<td align="right">1.00</td>
<td align="right">1.32</td>
<td align="right">0.00</td>
<td align="right">1.00</td>
<td align="right">2.00</td>
<td align="right">1.00</td>
<td align="right">0.59</td>
<td align="right">-1.65</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">Time_of_death</td>
<td align="right">8</td>
<td align="right">57,529</td>
<td align="right">30.69</td>
<td align="right">12.88</td>
<td align="right">30.18</td>
<td align="right">30.73</td>
<td align="right">13.65</td>
<td align="right">0.01</td>
<td align="right">64.15</td>
<td align="right">64.14</td>
<td align="right">0.01</td>
<td align="right">-0.66</td>
<td align="right">0.05</td>
</tr>
</tbody>
</table>
<p>In summary, there are 160,781 insureds, out of which 57,529, i.e. 35.78%, have died; the average age at purchase is about 40, and our portfolio has a high percentage of men (70%) and non-smokers (70%). The average BMI is 22.8 and the average blood pressure is 114.8, which are close to (but somewhat lower than) U.S. national averages; <span class="math inline">\(\color{red}{for\;details, \;see ...}\)</span></p>
<p>To illustrate the sales history, we plot the monthly sales of the company, which is given as Figure <a href="modeling-lifetimes.html#fig:MonthlySalesFigs">2.4</a>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1">monthly_sales &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">780</span>)</a>
<a class="sourceLine" id="cb13-2" title="2"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">780</span>){</a>
<a class="sourceLine" id="cb13-3" title="3">  monthly_sales[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(ins_data<span class="op">$</span>Month_of_Sale <span class="op">==</span><span class="st"> </span>i)</a>
<a class="sourceLine" id="cb13-4" title="4">}</a>
<a class="sourceLine" id="cb13-5" title="5"><span class="kw">plot</span>(monthly_sales,<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;green&quot;</span>, <span class="dt">main=</span><span class="st">&quot;Monthly Sales&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;month&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Sales&quot;</span>)</a>
<a class="sourceLine" id="cb13-6" title="6"><span class="kw">abline</span>(<span class="dt">h =</span> <span class="kw">mean</span>(monthly_sales), <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">lty =</span> <span class="dv">2</span>)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:MonthlySalesFigs"></span>
<img src="LifeCon_files/figure-html/MonthlySalesFigs-1.png" alt="Monthy sales for the synthetic mortality data" width="576" />
<p class="caption">
Figure 2.4: Monthy sales for the synthetic mortality data
</p>
</div>
<p>In summary, the company sells about 200 insurance contract each month, although there is some variation over the time; while sales initially increased, the company experience some ebbs and flows, potentially due to marketing efforts and/or the effectiveness of the products.</p>
<p>We now investigate the traits of the insureds for which various histograms are given as Figure <a href="modeling-lifetimes.html#fig:HistInsDataFigs">2.5</a>.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" title="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</a>
<a class="sourceLine" id="cb14-2" title="2"><span class="kw">hist</span>(ins_data<span class="op">$</span>Age,<span class="dt">main=</span><span class="st">&quot;Insured Age&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;age&quot;</span>, <span class="dt">border=</span><span class="st">&quot;red&quot;</span>, <span class="dt">col=</span><span class="st">&quot;green&quot;</span>)</a>
<a class="sourceLine" id="cb14-3" title="3"><span class="kw">hist</span>(ins_data<span class="op">$</span>BMI,<span class="dt">main=</span><span class="st">&quot;Body Mass Index&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;bmi&quot;</span>, <span class="dt">border=</span><span class="st">&quot;red&quot;</span>, <span class="dt">col=</span><span class="st">&quot;green&quot;</span>)</a>
<a class="sourceLine" id="cb14-4" title="4"><span class="kw">hist</span>(ins_data<span class="op">$</span>BloodPressure,<span class="dt">main=</span><span class="st">&quot;Systolic Blood Pressure&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;bp&quot;</span>, <span class="dt">border=</span><span class="st">&quot;red&quot;</span>, <span class="dt">col=</span><span class="st">&quot;green&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:HistInsDataFigs"></span>
<img src="LifeCon_files/figure-html/HistInsDataFigs-1.png" alt="Histograms  for the synthetic mortality data" width="768" />
<p class="caption">
Figure 2.5: Histograms for the synthetic mortality data
</p>
</div>
<p>Most individuals are in between thirty and fifty years of age when purchasing the coverage, but some sales to younger and some older individuals are observed. The <em>Body Mass Index (BMI)</em> is concentrated between 20 and 30, although there are some outliers with relatively large values. The systolic blood pressure is roughly bell shaped, with most applicants exhibiting blood pressure measurements at normal levels (below 120) or slightly elevated levels (120-130). We could further visualize the relationship between these three attributes by looking at the correlation correlation matrix corresponding to these three characteristics, which is given as Figure <a href="modeling-lifetimes.html#fig:CorrPlotInsDataFigs">2.6</a>.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1"><span class="kw">suppressWarnings</span>(<span class="kw">library</span>(corrplot))</a>
<a class="sourceLine" id="cb15-2" title="2">tmp_corr_ins_data &lt;-<span class="st"> </span><span class="kw">cor</span>(ins_data[,<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">6</span>)])</a>
<a class="sourceLine" id="cb15-3" title="3"><span class="kw">colnames</span>(tmp_corr_ins_data) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Age&quot;</span>, <span class="st">&quot;BMI&quot;</span>, <span class="st">&quot;BP&quot;</span>)</a>
<a class="sourceLine" id="cb15-4" title="4"><span class="kw">rownames</span>(tmp_corr_ins_data) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Age&quot;</span>, <span class="st">&quot;BMI&quot;</span>, <span class="st">&quot;BP&quot;</span>)</a>
<a class="sourceLine" id="cb15-5" title="5"><span class="kw">corrplot</span>(tmp_corr_ins_data, <span class="dt">method=</span><span class="st">&quot;circle&quot;</span>, <span class="dt">order=</span><span class="st">&quot;hclust&quot;</span>, <span class="dt">addCoef.col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">tl.col=</span><span class="st">&quot;black&quot;</span>, <span class="dt">tl.srt=</span><span class="dv">45</span>)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:CorrPlotInsDataFigs"></span>
<img src="LifeCon_files/figure-html/CorrPlotInsDataFigs-1.png" alt="Correlation matrix for the synthetic mortality data corresponding to age, BMI and BP (blood pressure)" width="960" />
<p class="caption">
Figure 2.6: Correlation matrix for the synthetic mortality data corresponding to age, BMI and BP (blood pressure)
</p>
</div>
<p>Clearly, high blood pressure and elevated BMI are positively associated, and an elevated blood pressure is more common for elderly insureds, which are common observations in many populations.</p>
<p>One of our main focus is the realized lifetime, which could only be observed for those individuals where a claim had been paid. We could thus plot the distribution of the age at death, which is illustrated in Figure <a href="modeling-lifetimes.html#fig:AgeDeathHistInsDataFigs">2.7</a>.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" title="1"><span class="kw">hist</span>(ins_data<span class="op">$</span>Age<span class="op">+</span>ins_data<span class="op">$</span>Time_of_death,<span class="dt">main=</span><span class="st">&quot;Age at Death&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;age&quot;</span>, <span class="dt">border=</span><span class="st">&quot;red&quot;</span>, <span class="dt">col=</span><span class="st">&quot;green&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:AgeDeathHistInsDataFigs"></span>
<img src="LifeCon_files/figure-html/AgeDeathHistInsDataFigs-1.png" alt="Age at Death for the synthetic mortality data" width="576" />
<p class="caption">
Figure 2.7: Age at Death for the synthetic mortality data
</p>
</div>
<p>Not surprisingly, the majority of deceased policyholders have died at higher ages, since the bulk of deaths are concentrated between seventy and ninety years old. There are a few individuals that died relatively young, and similarly a few that were close to achieving the centenarian status, though it should be noted that some policyholders at higher ages may still be alive. Indeed, the ages of five oldest individuals that are still alive are</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" title="1"><span class="kw">round</span>(<span class="kw">tail</span>(<span class="kw">sort</span>(ins_data[ins_data<span class="op">$</span>Claim <span class="op">==</span><span class="st"> &quot;NO&quot;</span>,<span class="dv">2</span>]<span class="op">+</span><span class="st"> </span>(<span class="dv">780</span> <span class="op">-</span><span class="st"> </span>ins_data[ins_data<span class="op">$</span>Claim <span class="op">==</span><span class="st"> &quot;NO&quot;</span>,<span class="dv">1</span>])<span class="op">/</span><span class="dv">12</span>),<span class="dv">5</span>), <span class="dt">digits =</span> <span class="dv">2</span>)</a></code></pre></div>
<pre><code>## [1]  99.17 100.25 100.42 101.50 102.92</code></pre>
<p>and thus, it is clear that we observe nor many centenarians.</p>
<p>It is intuitive that the number of deaths are associated with sales <span class="math inline">\(\color{red}{\text{not clear to me}}\)</span>, as is evident when plotting the number of deaths by the year of sale, which is displayed in Figure <a href="modeling-lifetimes.html#fig:DeathSalesPlotInsDataFigs">2.8</a>.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" title="1">annual_death &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">65</span>)</a>
<a class="sourceLine" id="cb19-2" title="2"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">65</span>){</a>
<a class="sourceLine" id="cb19-3" title="3">  <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">12</span>){</a>
<a class="sourceLine" id="cb19-4" title="4">    annual_death[i] &lt;-<span class="st"> </span>annual_death[i] <span class="op">+</span><span class="st"> </span><span class="kw">sum</span>(ins_data[ins_data<span class="op">$</span>Month_of_Sale <span class="op">==</span><span class="st"> </span>(i<span class="dv">-1</span>)<span class="op">*</span><span class="dv">12</span> <span class="op">+</span>j,<span class="dv">7</span>] <span class="op">==</span><span class="st"> &quot;YES&quot;</span>) </a>
<a class="sourceLine" id="cb19-5" title="5">  }</a>
<a class="sourceLine" id="cb19-6" title="6">}</a>
<a class="sourceLine" id="cb19-7" title="7"><span class="kw">plot</span>(annual_death,<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">4</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">main=</span><span class="st">&quot;Annual Deaths&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;Year&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Deaths&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:DeathSalesPlotInsDataFigs"></span>
<img src="LifeCon_files/figure-html/DeathSalesPlotInsDataFigs-1.png" alt="Annual deaths for the synthetic mortality data" width="576" />
<p class="caption">
Figure 2.8: Annual deaths for the synthetic mortality data
</p>
</div>
<p>We could investigate the relationship of the time of death to policyholder characteristics by creating a correlation plot amongst those that had already died. The correlation matrix appears as Figure <a href="modeling-lifetimes.html#fig:DeadCorrPlotInsDataFigs">2.9</a>.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" title="1"><span class="co">#suppressWarnings(library(corrplot))</span></a>
<a class="sourceLine" id="cb20-2" title="2">tmp_dead_corr_ins_data &lt;-<span class="st"> </span><span class="kw">cor</span>(ins_data[ins_data<span class="op">$</span>Claim <span class="op">==</span><span class="st"> &quot;YES&quot;</span>,<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">8</span>)])</a>
<a class="sourceLine" id="cb20-3" title="3"><span class="kw">colnames</span>(tmp_dead_corr_ins_data) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Age&quot;</span>, <span class="st">&quot;BMI&quot;</span>, <span class="st">&quot;BP&quot;</span>, <span class="st">&quot;TD&quot;</span>)</a>
<a class="sourceLine" id="cb20-4" title="4"><span class="kw">rownames</span>(tmp_dead_corr_ins_data) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Age&quot;</span>, <span class="st">&quot;BMI&quot;</span>, <span class="st">&quot;BP&quot;</span>, <span class="st">&quot;TD&quot;</span>)</a>
<a class="sourceLine" id="cb20-5" title="5"><span class="kw">corrplot</span>(tmp_dead_corr_ins_data, <span class="dt">method=</span><span class="st">&quot;circle&quot;</span>, <span class="dt">order=</span><span class="st">&quot;hclust&quot;</span>, <span class="dt">addCoef.col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">tl.col=</span><span class="st">&quot;black&quot;</span>, <span class="dt">tl.srt=</span><span class="dv">45</span>)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:DeadCorrPlotInsDataFigs"></span>
<img src="LifeCon_files/figure-html/DeadCorrPlotInsDataFigs-1.png" alt="Correlation matrix for the synthetic mortality data corresponding to age, BMI, BP (blood pressure) and TD (time of death)" width="960" />
<p class="caption">
Figure 2.9: Correlation matrix for the synthetic mortality data corresponding to age, BMI, BP (blood pressure) and TD (time of death)
</p>
</div>
<p>Hence, the time of death is (strongly) negatively associated with age, which is not surprising as elderly individuals are more likely to die. Similar behaviour is also observed for the BMI and blood pressure attributes that are negatively associated with the the time of death, but we should clarify that the BMI and blood pressure measurements are observed when the policy inception though these negative associations explain why such attributes are good predictors of the insured’s health. The pairwise correlation between age, BMI and blood pressure are in line with our findings from Figure <a href="modeling-lifetimes.html#fig:CorrPlotInsDataFigs">2.6</a> that includes all insureds irrespective of their life status.</p>
<p>Even this simple analysis could help in understanding why the life office should evaluate the individual risk per policy by taking into consideration the available information, and more importantly, to have a fair evaluation of the covariates with strong influence over the policy final payout.</p>
</div>
</div>
<div id="S:" class="section level2">
<h2><span class="header-section-number">2.2</span> Modeling Death</h2>
<p>The previous section has introduced various examples of mortality data. Clearly, the most relevant question to actuaries is how to use this piece of information in order to devise lifetime models that could become the basis for analyzing the life-contingent exposures, which we require a theoretical underpinning. This section provides with the minimal theoretical foundation related to the conventional framework for life-contingent modeling. We commence by introducing the most important concept of a lifetime random variable and the key actuarial quantities that allow for a formal interpretation of the data previously presented.</p>
<div id="lifetime-random-variable-and-its-distribution" class="section level3">
<h3><span class="header-section-number">2.2.1</span> Lifetime random variable and its distribution</h3>
<p>It should be first recognized that we have been focus on understanding the lifetime uncertainty for a given individual or (sub)population, where the life status has been assumed to be dichotomous, i.e. <em>alive</em> and <em>dead</em> are the only life status under observation. Clearly, this simplified assumption helps us to create a parsimonious presentation that is fit for its purpose at this very moment, though one could consider <em>multi-state models</em> – with multiple life status such as alive, death, temporary disability, permanent disability and any other long term health condition, etc. – or bespoke models that relates to specific life insurance products where the modeler could consider non-health related factors such as early termination of a contract that have an impact on the policy’s cashflows. Both cases require <em>multiple decrement modeling</em> that explain the transition in between different policy’s status in order to describe the complex risk structure of a policy with multiple benefits.</p>
<p>From now on, we only assume a dichotomous life model, i.e. alive/dead, where our primary goal is to evaluate the time of death of a given individual. The usual notation is the lifetime random variable <span class="math inline">\(T_x\)</span> that explains the remaining future lifetime for an individual of currently aged <span class="math inline">\(x\)</span>. The underlying assumption of such approach is that the future lifetime is fully predictable only by age, while all other data attributes such as sex, socio-economic factors, genetic and health history factors, etc. do not explain the target variable, i.e. time of death. Obviously, the mortality risk should include all possible sources of data and their attributes that could better differentiate the mortality risk amongst insureds or any any other words, to achieve equity in the pricing process. That is, we denote by <span class="math inline">\(T_{\bf{x}}\)</span> the lifetime random variable for an insured with many available observable attributes <span class="math inline">\(\bf{x}\)</span> from a feature space that includes more traits that the age <span class="math inline">\(\it{x}\)</span>. Therefore, the notation interchange in between <span class="math inline">\(\bf{x}\)</span> and <span class="math inline">\(\it{x}\)</span> will further reflect the feature space considered and/or available to the mortality risk modeller.</p>
<p>While the feature space is the key ingredient of the mortality model, we should reflect upon external pressures when choosing the feature space. For example, the use of genetic specific attributes for risk classification is under vast scrutiny by insurance ethical experts, since such pieces of information could lead to genetic discrimination, and therefore, there are regulatory constraints in using such attributes. Moreover, even the sex attribute – one of the most important mortality explanatory variable – is not always acceptable; for example, the European Union insurance regulations had imposed pricing neutrality with respect to sex factors for quite some time, which means that life and non-life insurance policies issued within the European Union market should price males and females at the same level if all other observable attributes are similar.</p>
<p>We are now ready to discuss the distribution of <span class="math inline">\(T_\bf{x}\)</span>/<span class="math inline">\(T_x\)</span> though we implicitly assume that sex is the only explanatory variable and thus, all definitions are mostly given for <span class="math inline">\(T_x\)</span> that apply to <span class="math inline">\(T_\bf{x}\)</span> if not explicitly stated. The random variable <span class="math inline">\(T_x\)</span> is defined on positive real values, <span class="math inline">\((0,\infty)\)</span>, though the lifetime is always finite, but we do not explicitly define the limiting/ultimate age that could be reached by an individual of age <span class="math inline">\(x\)</span>/<span class="math inline">\(\bf{x}\)</span>. By definition, let <span class="math inline">\(F_x\)</span> and <span class="math inline">\(S_x\)</span> be the <em>cumulative distribution function</em> and <em>survival function</em> of <em>T_x</em>, respectively, and thus, we write
<span class="math display">\[F_x(t):=\Pr(T_x\le t)\quad \text{and}\quad S_x(t):=\Pr(T_x &gt; t)=1-\Pr(T_x \le t)=1-F_x(t)\quad\text{for all}\;t&gt;0.\]</span>
While the above definitions are also available for <span class="math inline">\(T_\bf{x}\)</span>, there are slight differences in further derivations. Note that <span class="math inline">\(T_x\)</span> solely depends on the age <span class="math inline">\(x\)</span>, and thus, <span class="math inline">\(T_x\)</span> and <span class="math inline">\(T_0|T_0&gt;x\)</span> are identically distributed random variables; in other words, the future lifetime for <span class="math inline">\((x)\)</span> is the same as the future lifetime of a newborn give that this newborn reaches age <span class="math inline">\(x\)</span>, <span class="math inline">\(T_0&gt;x\)</span>. The mathematical formulations of this observation are given in the next equations:
<span class="math display">\[\begin{eqnarray*}
F_x(t) &amp;=&amp; Pr(T_x \le t) = Pr(T_x \le t \mid T_x&gt;0) = Pr(T_0-x \le t \mid T_0-x&gt;0)= Pr(T_0 \le x + t \mid T_0 &gt; x)\\
&amp;=&amp;\frac{\Pr(x&lt;T_0\leq x+t)}{\Pr(T_0&gt;x)}=\frac{F_0(x+t)-F_0(x)}{S_0(x)}=\frac{S_0(x)-S_0(x+t)}{S_0(x)}
\end{eqnarray*}\]</span>
and
<span class="math display">\[\begin{eqnarray*}
S_x(t) &amp;=&amp; Pr(T_x &gt; t) = Pr(T_x &gt; t \mid T_x &gt; 0) = Pr(T_0-x &gt; t \mid T_0-x&gt;0) = Pr(T_0 &gt; x+t \mid T_0&gt;x)\\
&amp;=&amp;\frac{\Pr(T_0&gt; x+t)}{\Pr(T_0&gt;x)}=\frac{S_0(x+t)}{S_0(x)}.
\end{eqnarray*}\]</span>
Similar mathematical formulations for <span class="math inline">\(T_\bf{x}\)</span> are not possible, since the future lifetime for <span class="math inline">\((x)\)</span> is explained by more traits than only the age attribute. That is, <span class="math inline">\(T_\bf{x}\)</span> could not be simply linked with the future lifetime a newborn that currently reached the set of characteristics <span class="math inline">\(\bf{x}\)</span> as we had done for <span class="math inline">\(T_x\)</span>.</p>
<p>The future lifetime random variable is naturally continuously distributed, but we further assume that is absolutely continuous, i.e. <span class="math inline">\(F_x\)</span> does not have jumps. Therefore, one could define
<span class="math display">\[f_x(t):=\frac{\partial F_x(t)}{\partial t}=\frac{\partial \big(1- S_x(t)\big)}{\partial t}=-\frac{\partial S_x(t)}{\partial t}\quad\text{for all}\;t&gt;0.\]</span>
which is known as the probability density function of <span class="math inline">\(T_x\)</span> and a similar definition could be written for the probability density function of <span class="math inline">\(T_\bf{x}\)</span>. The link between the current lifetime random variable and its equivalent newborn lifetime random variable is only possible for <span class="math inline">\(T_x\)</span>, and in that case we could write that
<span class="math display">\[f_x(t)=-\frac{\partial S_x(t)}{\partial t}=-\frac{\partial \left(\frac{S_0(x+t)}{S_0(x)}\right)}{\partial t}=-\frac{\frac{\partial S_0(x+t)}{\partial t}}{S_0(x)}=\frac{f_0(x+t)}{S_0(x)}\quad\text{for all}\;t&gt;0.\]</span>
Clearly, no immediate equivalent mathematical formulation for <span class="math inline">\(f_\bf{x}\)</span> in terms of the lifetime of a newborn could be provided.</p>
<p>The force of mortality, <span class="math inline">\(\mu_x\)</span>/<span class="math inline">\(\mu_\bf{x}\)</span>, represents the instantaneous mortality rate of <span class="math inline">\(x\)</span>/<span class="math inline">\(\bf{x}\)</span>
<span class="math display">\[\mu_x:=\frac{\partial F_x(t)}{\partial t}\mid t=0=-\frac{\partial S_x(t)}{\partial t}\mid t=0\quad\text{and}\quad\mu_\textbf{x}:=\frac{\partial F_\textbf{x}(t)}{\partial t}\mid t=0=-\frac{\partial S_\textbf{x}(t)}{\partial t}\mid t=0.\]</span>
We could further write that <span class="math inline">\(\mu_x=\frac{f_0(x)}{S_0(x)}\)</span>, but such simplification is not extendable to <span class="math inline">\(\mu_\bf{x}\)</span>. Finally, recall that
<span class="math display">\[
\mu_x=\frac{f_0(x)}{S_0(x)}=-\frac{S_0^{&#39;}(x)}{S_0(x)}=-\frac{\partial }{\partial x} \log S_0(x)\quad\text{for all}\quad x\ge 0,\]</span>
which in turn – after integrating the last expression – gives that
<span class="math display">\[
S_0(x) = \exp\left\{-\int_0^x \mu_t\;dt \right\}\quad\text{for all}\quad x\ge 0.
\]</span></p>
</div>
<div id="survival-and-mortality-probabilities" class="section level3">
<h3><span class="header-section-number">2.2.2</span> Survival and mortality probabilities</h3>
<p>The mathematical foundation of the lifetime random variable has been discussed in the previous section, and based on those definitions, we could provide the standard actuarial notations on survival and mortality probabilities. That is, the survival probability of <span class="math inline">\(x\)</span> at time <span class="math inline">\(t\)</span> is defined as follows:
<span class="math display">\[\begin{equation}
{_tp_x}:= S_x(t)\quad\text{for all}\;t&gt;0
\end{equation}\]</span>
and represents probability that individual <span class="math inline">\(x\)</span> survives <span class="math inline">\(t\)</span> more units of time. Further, the mortality probability of <span class="math inline">\(x\)</span> at time <span class="math inline">\(t\)</span> is defined as follows:
<span class="math display">\[\begin{equation}
{_tq_x}:= F_x(t)\quad\text{for all}\;t&gt;0
\end{equation}\]</span>
and represents probability that individual <span class="math inline">\(x\)</span> dies within the next <span class="math inline">\(t\)</span> units of time. Clearly, <span class="math inline">\({_tp_x}+{_tq_x}=1\)</span>, since the individual <span class="math inline">\(x\)</span> either dies or survives after <span class="math inline">\(t\)</span> units of time. By definition, we have that
<span class="math display">\[{_1p_x}:= {p_x}\quad\text{and}\quad {_1q_x} = {q_x}.\]</span>
Similar definitions are true for a high dimensional feature space, i.e. when <span class="math inline">\(x\)</span> is replaced by <span class="math inline">\(\bf{x}\)</span>.</p>
</div>
<div id="S:LifeExp" class="section level3">
<h3><span class="header-section-number">2.2.3</span> Complete expectation of life</h3>
<p>The <em>complete expectation of life</em> is an intuitive mortality indicator and represents the average remaining lifetime of <span class="math inline">\(x\)</span>, and is defined as follows:
<span class="math display">\[\stackrel{\circ}{e}_x:=E[T_x]=\int_0^\infty S_x(t)\;dt=\int_0^\infty {_tp_x}\;dt.\]</span>
Note that the second identity could be shown via integration by parts and keeping in mind that <span class="math inline">\(T_x\)</span> is a non-negative random variable with a finite expectation, which is an well-known result, but the proof is left to math enthusiast which is beyond the scope of this book.</p>
<p>Another centrality mortality measure is the <em>central death rate</em>, also known as <em>central rate of mortality</em>. This measure is defined as the average number of deaths each year that have characteristics <span class="math inline">\(\bf{x}\)</span> at the moment of death in the relevant observation period, divided by the average population with the same characteristics <span class="math inline">\(\bf{x}\)</span> over the same period, and is denoted as <span class="math inline">\(m_\bf{x}\)</span>. In practice, the observation period could be three to five years. For example, if we consider the U.S. mortality data, <span class="math inline">\(m_{50}\)</span> based on the observation period 2010 to 2014 would be the average number of deaths at age <span class="math inline">\(50\)</span> years across 2010, 2011, 2012, 2013 and 2014, divided by the average number of people aged <span class="math inline">\(50\)</span> years across 2010, 2011, 2012, 2013 and 2014; clearly, this example considers that age is the only explanatory variable to the mortality risk.</p>
<p><span class="math inline">\(\color{red}{\text{[Vali:] this is left over from Dani and I am not sure what you meant --}}\)</span> And then we can kind of use the different data sources in the different sections. For instance, when discussing analytic mortality laws we can fit parameters to the age-dependent life expectancies (moment-based), we can generate life tables using the mortality.org data (as in the R class exercises I sent) and then use simulated data for the non-parametric and the survival regression stuff. I would probably switch the order of sections D and E.</p>
</div>
</div>
<div id="S:AnalMortLaws" class="section level2">
<h2><span class="header-section-number">2.3</span> Analytical laws of mortality</h2>
<p>Actuarial practice relies on extensive mortality experience based on non-parametric and semi-parametric models. Early on mortality modeling had focus on simplified parametric models that depend on some parameters and are known as <em>Analytic Mortality Laws</em>; such models assume analytic survival or mortality functions, which have their own merits though the lack of sophistication is easily visible. From the pedagogical perspective, the analytical laws of mortality are good toy models that provide simple approximations of reality, which is the pure essence of any model.</p>
<p>Since we deal with simple mortality models, it would make sense to assume that mortality is age dependent only. It is well-known that any survival function takes the value 1 and 0 at the left and right end point of its distribution. Thus, if a newborn is assumed to have a known limited age <span class="math inline">\(\omega\)</span>, then <span class="math inline">\(S_0(0)=1\)</span> and <span class="math inline">\(S_0(\omega)=0\)</span>. One simple analytical example is the <em>De Moivre Mortality Law</em> which assumes a linear dependence of <span class="math inline">\(S_0\)</span>, i.e.
<span class="math display">\[
S_0(x) = 1 - \frac{x}{\omega}\quad\text{for all}\quad 0 \leq x \leq \omega.
\]</span>
Now, the force of mortality becomes
<span class="math display">\[
\mu_x= \frac{-S_0&#39;(x)}{S_0(x)} = \frac{\frac{1}{\omega}}{1 - \frac{x}{\omega}} = \frac{1}{\omega - x}\quad\text{for all}\quad 0 \leq x &lt; \omega.
\]</span>
A generalization of the above analytical mortality law is known as the <em>generalized De Moivre Law</em>, and corresponds to a survival function with the following parametrization
<span class="math display">\[
S_0(x) = \left(1 - \frac{x}{\omega}\right)^{\alpha}\quad\text{for all}\quad 0\leq x \leq \omega,
\]</span>
where the positive shape parameter <span class="math inline">\(\alpha\)</span> decides how far the survival function departs from the linear dependence. Then, its force of mortality becomes
<span class="math display">\[
\mu_x = \frac{\alpha/\omega\,(1-x/\omega)^{\alpha-1}}{(1-x/\omega)^{\alpha}} = \frac{\alpha}{\omega - x}\quad\text{for all}\quad 0\leq x \leq \omega.
\]</span></p>
<p>A slightly different approach is to impose a particular structure to the force of mortality. The simplest example is to consider a constant force of mortality model, i.e. <span class="math inline">\(\mu_t=\mu\)</span> for all <span class="math inline">\(t&gt;0\)</span>, which corresponds to an Exponentially distributed lifetime <span class="math inline">\(T_x\)</span> with
<span class="math display">\[
S_0(x) = e^{-\mu\,x}\quad\text{for all}\quad x\ge 0.
\]</span>
it is expected that the force of mortality is increasing over the time, which has been observed for the <em>De Moivre</em> and <em>generalized De Moivre</em> mortality laws, but not for the above constant force mortality model, which questions its validity to replicate the human mortality. A remedy to the constant force of mortality model is provided by the <em>Gompertz Mortality Law</em> and is given as follows:
<span class="math display">\[
\mu_x = B\cdot c^x \quad\text{for all}\quad x\ge 0\quad\text{with}\quad B&gt;0,\,c&gt;1.
\]</span>
Its survival function becomes
<span class="math display">\[
S_0(x) =\exp\left\{-\int_0^x \mu_t\;dt \right\}=\exp\left\{-\int_0^x B\cdot c^t\;dt \right\}=\exp\left\{-\frac{B \cdot c^t}{\log c}\Big\lvert_{t=0}^{t=x} \right\} =\exp\left\{ - \frac{B}{\log(c)} (c^x - 1)\right\}\quad\text{for all}\quad x\ge 0. 
\]</span>
A three parameter version of the <em>Gompertz Mortality Law</em> was proposed by Makeham, where an age-independent term is added and captures the external causes of death, i.e.
<span class="math display">\[
\mu_x = A + B\cdot c^x\quad\text{for all}\quad x\ge 0\quad\text{with}\quad B&gt;0,\,A+B\geq 0,\,c&gt;1,
\]</span>
and is known as the <em>Gompertz-Makeham Mortality Law</em> or <em>Makeham Mortality Law</em>. Then, its survival function could be derived as follows:
<span class="math display">\[\begin{eqnarray*}
S_0(x) &amp;=&amp;  \exp\left\{-\int_0^x \mu_t\,dt\right\}\\
&amp;=&amp; \exp\left\{-\int_0^x A\,dt\right\}\,\exp\left\{-\int_0^x B\cdot c^t\,dt\right\}\\
&amp;= &amp; \exp\{-A x\}\,\exp\left\{ - \frac{B}{\log(c)} (c^x - 1)\right\} \\
&amp;=&amp; \exp\left\{ - Ax - \frac{B}{\log(c)} (c^x - 1)\right\}.
\end{eqnarray*}\]</span></p>
<p>The last analytical mortality model is sufficiently rich to be further considered for fitting the U.S. life expectancy on the Gompertz-Makeham mortality law. For instance, the U.S. females data lead to the following parameters:</p>
<p><span class="math inline">\(\color{red}{\text{[Vali:] Did not change much in this part -- starts from here}}\)</span></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" title="1">S_<span class="dv">0</span> &lt;-<span class="st"> </span><span class="cf">function</span>(x,A,B,c) { <span class="kw">exp</span>(<span class="op">-</span><span class="st"> </span>A <span class="op">*</span><span class="st"> </span>x <span class="op">-</span><span class="st"> </span>B <span class="op">*</span><span class="st"> </span>(<span class="kw">exp</span>(c<span class="op">*</span>x) <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)<span class="op">/</span><span class="st"> </span>c) }</a>
<a class="sourceLine" id="cb21-2" title="2"></a>
<a class="sourceLine" id="cb21-3" title="3">le &lt;-<span class="st"> </span><span class="cf">function</span>(age,A,B,c){</a>
<a class="sourceLine" id="cb21-4" title="4">  Sfixed &lt;-<span class="st"> </span><span class="cf">function</span>(x){ <span class="kw">S_0</span>(x<span class="op">+</span>age,A,B,c)<span class="op">/</span><span class="kw">S_0</span>(age,A,B,c)}</a>
<a class="sourceLine" id="cb21-5" title="5">  res &lt;-<span class="st"> </span><span class="kw">integrate</span>(Sfixed,<span class="dt">lower =</span> <span class="dv">0</span>, <span class="dt">upper =</span> (<span class="dv">120</span><span class="op">-</span>age))<span class="op">$</span>value</a>
<a class="sourceLine" id="cb21-6" title="6">  <span class="kw">return</span>(res)</a>
<a class="sourceLine" id="cb21-7" title="7">}</a>
<a class="sourceLine" id="cb21-8" title="8"></a>
<a class="sourceLine" id="cb21-9" title="9"><span class="co">#We just use the resulting parameters here and do not carry out the following routine</span></a>
<a class="sourceLine" id="cb21-10" title="10"><span class="co">#tomin &lt;- function(x){</span></a>
<a class="sourceLine" id="cb21-11" title="11"><span class="co">#  res &lt;- 0</span></a>
<a class="sourceLine" id="cb21-12" title="12"><span class="co">#  for (i in 1:5){</span></a>
<a class="sourceLine" id="cb21-13" title="13"><span class="co">#    res &lt;- res + (us_les[i,4] - le((i-1)*20,0.0001*(1+x[1]/100),0.000007*(1+x[2]/100),0.11*(1+x[3]/100)))^2</span></a>
<a class="sourceLine" id="cb21-14" title="14"><span class="co">#  }</span></a>
<a class="sourceLine" id="cb21-15" title="15"><span class="co">#  return(res)</span></a>
<a class="sourceLine" id="cb21-16" title="16"><span class="co">#}</span></a>
<a class="sourceLine" id="cb21-17" title="17"><span class="co">#library(pracma)</span></a>
<a class="sourceLine" id="cb21-18" title="18"><span class="co">#res &lt;- fminsearch(tomin,c(0,0,0))</span></a>
<a class="sourceLine" id="cb21-19" title="19"><span class="co">#A_opt_fem &lt;- A*(1+res$xmin[1]/100)</span></a>
<a class="sourceLine" id="cb21-20" title="20"><span class="co">#B_opt_fem &lt;- B*(1+res$xmin[2]/100)</span></a>
<a class="sourceLine" id="cb21-21" title="21"><span class="co">#c_opt_fem &lt;- c*(1+res$xmin[3]/100)</span></a>
<a class="sourceLine" id="cb21-22" title="22"></a>
<a class="sourceLine" id="cb21-23" title="23">A_opt_fem &lt;-<span class="st"> </span><span class="fl">0.0005385767</span></a>
<a class="sourceLine" id="cb21-24" title="24">A_opt_fem </a></code></pre></div>
<pre><code>## [1] 0.0005385767</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" title="1">B_opt_fem &lt;-<span class="st"> </span><span class="fl">1.119213e-05</span></a>
<a class="sourceLine" id="cb23-2" title="2">B_opt_fem</a></code></pre></div>
<pre><code>## [1] 0.00001119213</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" title="1">c_opt_fem &lt;-<span class="st"> </span><span class="fl">0.1031558</span></a>
<a class="sourceLine" id="cb25-2" title="2">c_opt_fem</a></code></pre></div>
<pre><code>## [1] 0.1031558</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" title="1"><span class="co">#When running for males</span></a>
<a class="sourceLine" id="cb27-2" title="2"><span class="co">#A_opt_male &lt;- 0.0008564071</span></a>
<a class="sourceLine" id="cb27-3" title="3"><span class="co">#B_opt_male &lt;- 3.544491e-05</span></a>
<a class="sourceLine" id="cb27-4" title="4"><span class="co">#c_opt_male &lt;- 0.09276854</span></a></code></pre></div>
<p>which match the U.S. female life expectancies quite well:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" title="1">tmp &lt;-<span class="st"> </span>us_les[,<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">4</span>)]</a>
<a class="sourceLine" id="cb28-2" title="2">tmp<span class="op">$</span>fitted &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">5</span>)</a>
<a class="sourceLine" id="cb28-3" title="3"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">5</span>){</a>
<a class="sourceLine" id="cb28-4" title="4">  tmp[i,<span class="dv">3</span>] &lt;-<span class="st"> </span><span class="kw">le</span>((i<span class="dv">-1</span>)<span class="op">*</span><span class="dv">20</span>,A_opt_fem,B_opt_fem,c_opt_fem)</a>
<a class="sourceLine" id="cb28-5" title="5">}</a>
<a class="sourceLine" id="cb28-6" title="6"><span class="kw">kable</span>(tmp, <span class="dt">digits =</span> <span class="dv">2</span>, <span class="dt">format.args =</span> <span class="kw">list</span>(<span class="dt">big.mark =</span> <span class="st">&quot;,&quot;</span>))</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">Age</th>
<th align="right">Female</th>
<th align="right">fitted</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="right">81.1</td>
<td align="right">81.05</td>
</tr>
<tr class="even">
<td align="right">20</td>
<td align="right">61.8</td>
<td align="right">61.87</td>
</tr>
<tr class="odd">
<td align="right">40</td>
<td align="right">42.6</td>
<td align="right">42.72</td>
</tr>
<tr class="even">
<td align="right">60</td>
<td align="right">24.7</td>
<td align="right">24.49</td>
</tr>
<tr class="odd">
<td align="right">80</td>
<td align="right">9.8</td>
<td align="right">9.90</td>
</tr>
</tbody>
</table>
<p>The pictorial representation of the survival function appears as Figure <a href="modeling-lifetimes.html#fig:SurvPlotFemUSDataFigs">2.10</a>.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" title="1"><span class="kw">plot</span>(<span class="kw">S_0</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">120</span>,A_opt_fem,B_opt_fem,c_opt_fem), <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">3</span>, <span class="dt">col =</span> <span class="st">&quot;green&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;Gompertz-Makeham Mortality Model&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;age&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;S_0&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:SurvPlotFemUSDataFigs"></span>
<img src="LifeCon_files/figure-html/SurvPlotFemUSDataFigs-1.png" alt="Fitted Survival Curve" width="576" />
<p class="caption">
Figure 2.10: Fitted Survival Curve
</p>
</div>
<p>And here are the calibrated versions: … <span class="math inline">\(\color{red}{\text{[Vali:] Did not change much in this part -- ends here.}}\)</span></p>
</div>
<div id="S:LifeTab" class="section level2">
<h2><span class="header-section-number">2.4</span> Life tables and their functions</h2>
<p>Life insurance policies have a complex benefit structure that requires knowledge upon the probability of paying the benefits besides many other risk modeling parameters. Policy pricing, meeting the regulatory requirements and understanding the life portfolio risk performance are all actuarial evaluations that rely on these risk modeling parameters, but the mortality risk plays an important role for which sophisticated stochastic models are possible. A rather simpler way is to construct <em>life tables</em> that are not only of pedagogical use, but create a simplified platform of discussions for a smooth transition to understanding more complex mortality models.</p>
<p>We first start with creating some simple life tables in Section <a href="modeling-lifetimes.html#S:LifeTabBasic">2.4.1</a> that are based on the U.S. mortality data, and we then move on into Section <a href="modeling-lifetimes.html#S:LifeTabMImpr">2.4.2</a> that provides some refinements of these life tables.</p>
<div id="S:LifeTabBasic" class="section level3">
<h3><span class="header-section-number">2.4.1</span> Life table based on U.S. population data</h3>
<p>The central focus of this section is to create some simple life tables and to validate our empirical results by revealing the main traits of a generic mortality data. The U.S. population data are only included in our analysis, and we start by looking into <em>central death rates</em> based on deaths and exposures. Before giving the summary results, here are some oh these computation are made; by looking at the main data from <code>HMD_Expo.csv</code> and <code>HMD_Deaths.csv</code>, one could retrieve the 1935-1939 exposures and deaths for individuals aged 0 as follows:</p>
<p><span class="math display">\[
\begin{equation*}
\begin{array}{lccc}
                &amp;\text{Female}    &amp;   \text{Male}     &amp;     \text{Total}\\
\text{Exposures}&amp;   4,869,267.21 &amp;  5,057,569.27    &amp; 9,926,836.48\\
\text{Deaths}    &amp;    253,145.89    &amp;  335,492       &amp; 588,637.89
\end{array}
\end{equation*}
\]</span></p>
<p>The above could help with finding the corresponding 1935-1939 central death rates for the female, male and entire U.S. population data, and the calculations are given below:
<span class="math display">\[
\begin{eqnarray*}
m_o^{Female}&amp;=&amp;\frac{253,145.89}{4,869,267.21}=0.05198849828\\ 
m_o^{Male}&amp;=&amp;\frac{335,492}{5,057,569.27}=0.06633463272\\
m_o^{Total}&amp;=&amp;\frac{588,637.89}{9,926,836.48}=0.05929763134.
\end{eqnarray*}
\]</span></p>
<p>We could now provide the summary of the central death rates as follows:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" title="1"><span class="kw">library</span>(data.table)</a>
<a class="sourceLine" id="cb30-2" title="2">us_mx &lt;-<span class="st"> </span>us_deaths </a>
<a class="sourceLine" id="cb30-3" title="3">us_mx[,<span class="dv">4</span><span class="op">:</span><span class="dv">6</span>] &lt;-<span class="st"> </span>us_deaths[,<span class="dv">4</span><span class="op">:</span><span class="dv">6</span>] <span class="op">/</span><span class="st"> </span>us_exp[,<span class="dv">4</span><span class="op">:</span><span class="dv">6</span>]</a>
<a class="sourceLine" id="cb30-4" title="4"><span class="kw">kable</span>(<span class="kw">head</span>(us_mx), <span class="dt">align =</span> <span class="st">&quot;cccrrr&quot;</span>)</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="center">Year_start</th>
<th align="center">Year_end</th>
<th align="center">Age</th>
<th align="right">Female</th>
<th align="right">Male</th>
<th align="right">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1935</td>
<td align="center">1939</td>
<td align="center">0</td>
<td align="right">0.051988498</td>
<td align="right">0.066334633</td>
<td align="right">0.059297631</td>
</tr>
<tr class="even">
<td align="center">1935</td>
<td align="center">1939</td>
<td align="center">1</td>
<td align="right">0.007498031</td>
<td align="right">0.008542782</td>
<td align="right">0.008027575</td>
</tr>
<tr class="odd">
<td align="center">1935</td>
<td align="center">1939</td>
<td align="center">2</td>
<td align="right">0.003460997</td>
<td align="right">0.004043794</td>
<td align="right">0.003755912</td>
</tr>
<tr class="even">
<td align="center">1935</td>
<td align="center">1939</td>
<td align="center">3</td>
<td align="right">0.002413097</td>
<td align="right">0.002808973</td>
<td align="right">0.002613459</td>
</tr>
<tr class="odd">
<td align="center">1935</td>
<td align="center">1939</td>
<td align="center">4</td>
<td align="right">0.001956863</td>
<td align="right">0.002217746</td>
<td align="right">0.002088776</td>
</tr>
<tr class="even">
<td align="center">1935</td>
<td align="center">1939</td>
<td align="center">5</td>
<td align="right">0.001619364</td>
<td align="right">0.001869059</td>
<td align="right">0.001746192</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" title="1"><span class="co">#displaying the very end of the table similar to the very top of the table requires a few more steps</span></a>
<a class="sourceLine" id="cb31-2" title="2">tmp_tail_us_mx &lt;-<span class="st"> </span><span class="kw">tail</span>(us_mx); <span class="kw">rownames</span>(tmp_tail_us_mx) &lt;-<span class="st"> </span><span class="ot">NULL</span></a>
<a class="sourceLine" id="cb31-3" title="3"><span class="kw">kable</span>(tmp_tail_us_mx, <span class="dt">align =</span> <span class="st">&quot;cccrrr&quot;</span>)</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="center">Year_start</th>
<th align="center">Year_end</th>
<th align="center">Age</th>
<th align="right">Female</th>
<th align="right">Male</th>
<th align="right">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">2010</td>
<td align="center">2014</td>
<td align="center">105</td>
<td align="right">0.544747305</td>
<td align="right">0.648959567</td>
<td align="right">0.555566429</td>
</tr>
<tr class="even">
<td align="center">2010</td>
<td align="center">2014</td>
<td align="center">106</td>
<td align="right">0.566723146</td>
<td align="right">0.587329097</td>
<td align="right">0.568728261</td>
</tr>
<tr class="odd">
<td align="center">2010</td>
<td align="center">2014</td>
<td align="center">107</td>
<td align="right">0.557618769</td>
<td align="right">0.670120241</td>
<td align="right">0.568175534</td>
</tr>
<tr class="even">
<td align="center">2010</td>
<td align="center">2014</td>
<td align="center">108</td>
<td align="right">0.636754582</td>
<td align="right">0.611534481</td>
<td align="right">0.634501769</td>
</tr>
<tr class="odd">
<td align="center">2010</td>
<td align="center">2014</td>
<td align="center">109</td>
<td align="right">0.659418665</td>
<td align="right">0.571037316</td>
<td align="right">0.650733498</td>
</tr>
<tr class="even">
<td align="center">2010</td>
<td align="center">2014</td>
<td align="center">110</td>
<td align="right">0.593688157</td>
<td align="right">0.520304886</td>
<td align="right">0.584736850</td>
</tr>
</tbody>
</table>
<p>Based on the five year counting of deaths and exposures, we have displayed only the early ages central death rates based on the first period of observation, i.e. 1935-1939, and the upper higher ages central death rates based on the last period of observation, i.e. 2010-2014. The data show the expected trend that females show lower rates than the males. Moreover, besides the infantile mortality, all low ages death rates follow a decreasing pattern with respect to the age factor, which is also observable for high ages with the caveat that a higher uncertainty is present at such ages due to the relative smaller sample size.</p>
<p>Let’s now construct a mortality life table using the 2010-2014 U.S. Females and Males data, and we first pull out the previous pieces of information regarding to the 2010-2014 central death rates, which are only the first elements of these two life table.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" title="1">us_mx_fem_<span class="dv">2014</span> &lt;-<span class="st"> </span>us_mx[us_mx<span class="op">$</span>Year_start <span class="op">==</span><span class="st"> </span><span class="dv">2010</span>,<span class="op">-</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">6</span>)]</a>
<a class="sourceLine" id="cb32-2" title="2"><span class="kw">colnames</span>(us_mx_fem_<span class="dv">2014</span>)[<span class="kw">colnames</span>(us_mx_fem_<span class="dv">2014</span>)<span class="op">==</span><span class="st">&quot;Female&quot;</span>] &lt;-<span class="st"> &quot;mx US Females&quot;</span></a>
<a class="sourceLine" id="cb32-3" title="3">tmp_head_us_mx_fem_<span class="dv">2014</span> &lt;-<span class="st"> </span><span class="kw">head</span>(us_mx_fem_<span class="dv">2014</span>); <span class="kw">rownames</span>(tmp_head_us_mx_fem_<span class="dv">2014</span>) &lt;-<span class="st"> </span><span class="ot">NULL</span></a>
<a class="sourceLine" id="cb32-4" title="4"><span class="kw">kable</span>(<span class="kw">head</span>(tmp_head_us_mx_fem_<span class="dv">2014</span>), <span class="dt">align =</span> <span class="st">&quot;ccr&quot;</span>)</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="center">Year_start</th>
<th align="center">Age</th>
<th align="right">mx US Females</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">2010</td>
<td align="center">0</td>
<td align="right">0.005461737</td>
</tr>
<tr class="even">
<td align="center">2010</td>
<td align="center">1</td>
<td align="right">0.000379927</td>
</tr>
<tr class="odd">
<td align="center">2010</td>
<td align="center">2</td>
<td align="right">0.000224890</td>
</tr>
<tr class="even">
<td align="center">2010</td>
<td align="center">3</td>
<td align="right">0.000169394</td>
</tr>
<tr class="odd">
<td align="center">2010</td>
<td align="center">4</td>
<td align="right">0.000138322</td>
</tr>
<tr class="even">
<td align="center">2010</td>
<td align="center">5</td>
<td align="right">0.000119244</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" title="1">us_mx_mal_<span class="dv">2014</span> &lt;-<span class="st"> </span>us_mx[us_mx<span class="op">$</span>Year_start <span class="op">==</span><span class="st"> </span><span class="dv">2010</span>,<span class="op">-</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">6</span>)]</a>
<a class="sourceLine" id="cb33-2" title="2"><span class="kw">colnames</span>(us_mx_mal_<span class="dv">2014</span>)[<span class="kw">colnames</span>(us_mx_mal_<span class="dv">2014</span>)<span class="op">==</span><span class="st">&quot;Male&quot;</span>] &lt;-<span class="st"> &quot;mx US Males&quot;</span></a>
<a class="sourceLine" id="cb33-3" title="3">tmp_head_us_mx_mal_<span class="dv">2014</span> &lt;-<span class="st"> </span><span class="kw">head</span>(us_mx_mal_<span class="dv">2014</span>); <span class="kw">rownames</span>(tmp_head_us_mx_mal_<span class="dv">2014</span>) &lt;-<span class="st"> </span><span class="ot">NULL</span></a>
<a class="sourceLine" id="cb33-4" title="4"><span class="kw">kable</span>(<span class="kw">head</span>(tmp_head_us_mx_mal_<span class="dv">2014</span>), <span class="dt">align =</span> <span class="st">&quot;ccr&quot;</span>)</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="center">Year_start</th>
<th align="center">Age</th>
<th align="right">mx US Males</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">2010</td>
<td align="center">0</td>
<td align="right">0.006554279</td>
</tr>
<tr class="even">
<td align="center">2010</td>
<td align="center">1</td>
<td align="right">0.000441664</td>
</tr>
<tr class="odd">
<td align="center">2010</td>
<td align="center">2</td>
<td align="right">0.000298869</td>
</tr>
<tr class="even">
<td align="center">2010</td>
<td align="center">3</td>
<td align="right">0.000225097</td>
</tr>
<tr class="odd">
<td align="center">2010</td>
<td align="center">4</td>
<td align="right">0.000184733</td>
</tr>
<tr class="even">
<td align="center">2010</td>
<td align="center">5</td>
<td align="right">0.000145992</td>
</tr>
</tbody>
</table>
<p>The second elements of our life tables require computing the annual death probabilities <span class="math inline">\(q_x\)</span> from <span class="math inline">\(m_x\)</span> for which some background information is needed. An intuitive definition of the central death rate is given in Section <a href="modeling-lifetimes.html#S:LifeExp">2.2.3</a>, which is the ratio between the expected deaths and average population within a given observation period. A more mathematical formulation is possible when the reference period is reduced to one year for a population of 1, and is given as follows:<br />
<span class="math display">\[
m_{\bf{x}}:=\frac{E[I_{T_{\bf{x}}\le1}]}{E\big[\min\big(T_{\bf{x}},1\big)\big]},
\]</span>
where <span class="math inline">\(I_{\cdot}\)</span> is the indicator function for which <span class="math inline">\(I_A\)</span> takes the values 1 and 0 if <span class="math inline">\(A\)</span> is true and false, respectively. The nominator represents the theoretical expected deaths since
<span class="math display">\[E[I_{T_{\bf{x}}\le 1}]=\int_0^{\infty} I_{t\le1}\cdot f_{\bf{x}}(t)\;dt=\int_0^1 f_{\bf{x}}(t)\;dt=\Pr(T_{\bf{x}}\le1)=q_{\bf{x}}.\]</span></p>
<p>Moreover, the denominator clearly represents the theoretical number of survivors and could be further derived
<span class="math display">\[
E\big[\min\big(T_{\bf{x}},1\big)\big]=\int_0^\infty \Pr\Big(\min\big(T_{\bf{x}},1\big)&gt;t\Big)\;dt=\int_0^1 \Pr\big(T_{\bf{x}}&gt;t\big)\;dt=\int_0^1 S_{\bf{x}}(t)\;dt=\int_0^1 {_tp_{\bf{x}}}\;dt.
\]</span></p>
<p>Note that the first identity could be shown via integration by parts. Finally, combining altogether gives that
<span class="math display">\[
m_{\bf{x}}=\frac{q_{\bf{x}}}{\int_0^1 {_tp_{\bf{x}}}\;dt}.
\]</span></p>
<p>Annual death probabilities could be estimated on observed central death rates by making some fractional age assumptions. One simple fractional age assumption considers a constant force of mortality over the period of interest, i.e. one year since we compute the one year death rates, and this assumption is known as the <em>constant force assumption</em>. Let’s consider the case in which age is the only explanatory variable, and thus, under the constant force assumption we have that
<span class="math display">\[
_sq_x=F_x(s)=\frac{S_0(x)-S_0(x+s)}{S_0(x)}=\frac{\exp\left\{-\int_0^x \mu_t\;dt \right\}-\exp\left\{-\int_0^{x+s} \mu_t\;dt \right\}}{\exp\left\{-\int_0^x \mu_t\;dt \right\}}=1-\exp\left\{-\int_x^{x+s} \mu_t\;dt \right\}=1-e^{-\mu^*_{x} \cdot s}
\]</span>
and
<span class="math display">\[
_sp_x=\exp\left\{-\int_x^{x+s} \mu_t\;dt\right\}=e^{-\mu^*_x \cdot s}
\]</span>
for all <span class="math inline">\(0\le s\le 1\)</span>, where <span class="math inline">\(\mu^*_{x}\)</span> is the constant force of mortality over the ages <span class="math inline">\(x\)</span> and <span class="math inline">\(x+1\)</span>. In turn, one may get that
<span class="math display">\[
m_{x}=\frac{q_x}{\int_0^1 {_tp_x}\;dt}=\frac{1-e^{-\mu^*_x}}{\int_0^1 e^{-\mu^*_x \cdot t}\;dt}=\frac{1-e^{-\mu^*_x}}{\big(1-e^{-\mu^*_x}\big)/\mu^*_x}=\mu^*_x.
\]</span></p>
<p>The fractional age assumptions allow us to determine the one year death probability curve, and under the constant force assumption, one may estimate the one death probabilities as follows:
<span class="math display">\[q_x\approx 1-e^{-\mu^*_{x}}\approx 1-e^{-m_x}\quad\text{for all integers}\quad x.\]</span>
The death probability curves for the U.S. Females data are depicted in both original and logarithmic scales, and displayed as Figure <a href="modeling-lifetimes.html#fig:QxUSFemDataFigs">2.11</a>.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" title="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb34-2" title="2">us_mx_fem_<span class="dv">2014</span><span class="op">$</span>qx &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">-</span><span class="kw">exp</span>(<span class="op">-</span>us_mx_fem_<span class="dv">2014</span><span class="op">$</span>mx)</a>
<a class="sourceLine" id="cb34-3" title="3"><span class="kw">plot</span>(us_mx_fem_<span class="dv">2014</span><span class="op">$</span>qx,<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">main=</span><span class="st">&quot;Original scale&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;age&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;q_x&quot;</span>,<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="fl">1.0</span>))</a>
<a class="sourceLine" id="cb34-4" title="4"><span class="kw">lines</span>(us_mx_fem_<span class="dv">2014</span><span class="op">$</span>mx,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</a>
<a class="sourceLine" id="cb34-5" title="5"><span class="kw">plot</span>(<span class="kw">log</span>(us_mx_fem_<span class="dv">2014</span><span class="op">$</span>qx, <span class="dt">base =</span> <span class="dv">10</span>),<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">main=</span><span class="st">&quot;Log scale&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;age&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;q_x&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:QxUSFemDataFigs"></span>
<img src="LifeCon_files/figure-html/QxUSFemDataFigs-1.png" alt="One year death probability curve (in blue) and central death rate (in red) for the 2010-2014 U.S. Females data across all ages" width="768" />
<p class="caption">
Figure 2.11: One year death probability curve (in blue) and central death rate (in red) for the 2010-2014 U.S. Females data across all ages
</p>
</div>
<p>Similar pictorial representations for the U.S. Males data appear in Figure <a href="modeling-lifetimes.html#fig:QxUSMalDataFigs">2.12</a>.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" title="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb35-2" title="2">us_mx_mal_<span class="dv">2014</span><span class="op">$</span>qx &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">-</span><span class="kw">exp</span>(<span class="op">-</span>us_mx_mal_<span class="dv">2014</span><span class="op">$</span>mx)</a>
<a class="sourceLine" id="cb35-3" title="3"><span class="kw">plot</span>(us_mx_mal_<span class="dv">2014</span><span class="op">$</span>qx,<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">main=</span><span class="st">&quot;Original scale&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;age&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;q_x&quot;</span>,<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="fl">1.0</span>))</a>
<a class="sourceLine" id="cb35-4" title="4"><span class="kw">lines</span>(us_mx_mal_<span class="dv">2014</span><span class="op">$</span>mx,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</a>
<a class="sourceLine" id="cb35-5" title="5"><span class="kw">plot</span>(<span class="kw">log</span>(us_mx_mal_<span class="dv">2014</span><span class="op">$</span>qx, <span class="dt">base =</span> <span class="dv">10</span>),<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">main=</span><span class="st">&quot;Log scale&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;age&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;q_x&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:QxUSMalDataFigs"></span>
<img src="LifeCon_files/figure-html/QxUSMalDataFigs-1.png" alt="One year death probability curve (in blue) and central death rate (in red) for the 2010-2014 U.S. Males data across all ages" width="768" />
<p class="caption">
Figure 2.12: One year death probability curve (in blue) and central death rate (in red) for the 2010-2014 U.S. Males data across all ages
</p>
</div>
<p>As we can see, <span class="math inline">\(q_x\)</span> and <span class="math inline">\(m_x\)</span> are similar with the exception of the later years, which is not surprising since <span class="math inline">\(1-e^{-y}\approx y\)</span> for <span class="math inline">\(y\)</span> sufficiently small and by keeping on mind that the central death rates are small at all ages except of high ages. As expected, the log scale plots from Figures <a href="modeling-lifetimes.html#fig:QxUSFemDataFigs">2.11</a> and <a href="modeling-lifetimes.html#fig:QxUSMalDataFigs">2.12</a> are more informative in the sense that the log scale reveals the marginal changes over various ages, and we now combined the two log scaled curves into Figure <a href="modeling-lifetimes.html#fig:QxUSFemMalDataFigs">2.13</a>.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" title="1"><span class="kw">plot</span>(<span class="kw">log</span>(us_mx_fem_<span class="dv">2014</span><span class="op">$</span>qx, <span class="dt">base =</span> <span class="dv">10</span>), <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">main=</span><span class="st">&quot;Log scale&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;age&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;q_x&quot;</span>)</a>
<a class="sourceLine" id="cb36-2" title="2"><span class="kw">lines</span>(<span class="kw">log</span>(us_mx_mal_<span class="dv">2014</span><span class="op">$</span>qx, <span class="dt">base =</span> <span class="dv">10</span>), <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:QxUSFemMalDataFigs"></span>
<img src="LifeCon_files/figure-html/QxUSFemMalDataFigs-1.png" alt="One year death probability curve for the 2010-2014 U.S. Females (in blue) and Males (in red) data across all ages" width="576" />
<p class="caption">
Figure 2.13: One year death probability curve for the 2010-2014 U.S. Females (in blue) and Males (in red) data across all ages
</p>
</div>
<p>Figure <a href="modeling-lifetimes.html#fig:QxUSFemMalDataFigs">2.13</a> shows the usual higher mortality rates for males than for females, but also extremely pronounced differences at ages 16 to 40 that could be explained by social factors that are specific to U.S. Males at post adolescence ages; moreover, significant differences at ages 50 to 70 are also observed, and are due to health related factors that males around the world tend to be exposed earlier than females.</p>
<p>We are now able to construct life tables based on the U.S. mortality data, but we first provide a brief introduction to the concept of life tables. A <em>life table</em> contains various pieces of information about the mortality risk exhibit by individuals from a targeted age span; death of survivorship elements are displayed based on the observational data. More specific mortality rates due to seasonal epidemics, disability, etc., are usually not included. More complex life tables could be produced for multi-state models that we mentioned before, and are known as <em>multi-state life table</em>.</p>
<p>A life table is known as <em>period life table</em> if the prevalence rates – useful for health related causes of decrement – or mortality rates are observed during a specific time period of a certain population. On the contrary, a <em>cohort life table</em> is generated by collating these rates from a specific population observed over its entire lifetime, i.e. from early birth – all individuals are assumed to be born during the same time period – until the observational group is extincted. Both life tables have their own merits, but the cohort life tables tend to be more popular in the actuarial practice
and demography, since mortality experts are particularly interested into understanding the mortality patterns within subpopulations for actuarial calculations and advising the economic and social policy-makers. Given our available U.S. mortality data, we are only able to provide period life tables.</p>
<p>Our life table examples are given for a dichotomous mortality model with dead/alive possible life status for which age and sex are the only focal mortality explanatory variables. We restrict to the 2010-2014 U.S. mortality data and display the death probabilities, i.e. <span class="math inline">\(q_x\)</span>’s, central death rate, i.e. <span class="math inline">\(m_x\)</span>’s and <span class="math inline">\(l_x\)</span>’s for a given life table <em>radix</em>, i.e. <span class="math inline">\(l_0\)</span>; these are displayed for all ages, but separately for females and males when <span class="math inline">\(l_0\)</span> is chosen to be 1,000,000, which is an ad-hoc choice though other choices like 100,000 would be possible as well. One could view the third elements of our life table, i.e. <span class="math inline">\(l_x\)</span>, as the expected number of individuals at risk with characteristics <span class="math inline">\(x\)</span>, which is purely the age in this case given that the data are already separated by sex. Therefore, we have that
<span class="math display">\[
_sp_x=\frac{l_{x+t}}{l_x}\quad\text{for all}\quad x,t\ge0,
\]</span>
which in turn leads
<span class="math display">\[l_{x+1}=l_x\cdot p_x=l_x\big(1-q_x\big)\approx l_x\cdot e^{-m_x}\quad\text{for all integers}\quad x.\]</span>
under the constant force of mortality assumption. For example,</p>
<p><span class="math display">\[
\begin{eqnarray*}
\begin{array}{lllll}
l_0^{Female}&amp;=&amp;l_0\big(1-q_0^{Female}\big)&amp;\approx&amp; l_0\cdot \exp\big(-m_0^{Female}\big)&amp;=&amp;1,000,000\cdot e^{-0.005461737}&amp;=&amp; 994,553.151168\\
l_0^{Male}  &amp;=&amp;l_0\big(1-q_0^{Male}\big)  &amp;\approx&amp; l_0\cdot \exp\big(-m_0^{Male}\big)  &amp;=&amp;1,000,000\cdot e^{-0.006554279}&amp;=&amp; 993,467.153436,
\end{array}
\end{eqnarray*}
\]</span></p>
<p>which are quite close to the exact values 994,553.151225 and 993,467.1533967, respectively that are displayed on the actual life tables that follow after Figure <a href="modeling-lifetimes.html#fig:LxMalFemDataFigs">2.14</a>. The <span class="math inline">\(l_x\)</span> values are now plotted in Figure <a href="modeling-lifetimes.html#fig:LxMalFemDataFigs">2.14</a> where once again the female subpopulation shows higher survivorship trend than the male subpopulation.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" title="1">lf &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>,<span class="kw">length</span>(us_mx_fem_<span class="dv">2014</span><span class="op">$</span>mx))</a>
<a class="sourceLine" id="cb37-2" title="2">lf[<span class="dv">1</span>] &lt;-<span class="st"> </span><span class="dv">1000000</span></a>
<a class="sourceLine" id="cb37-3" title="3"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="op">:</span><span class="dv">111</span>){</a>
<a class="sourceLine" id="cb37-4" title="4">  lf[i] =<span class="st"> </span>lf[i<span class="dv">-1</span>] <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span><span class="op">-</span>us_mx_fem_<span class="dv">2014</span>[i<span class="dv">-1</span>,<span class="dv">4</span>]) </a>
<a class="sourceLine" id="cb37-5" title="5">                }</a>
<a class="sourceLine" id="cb37-6" title="6">lm &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>,<span class="kw">length</span>(us_mx_mal_<span class="dv">2014</span><span class="op">$</span>mx))</a>
<a class="sourceLine" id="cb37-7" title="7">lm[<span class="dv">1</span>] &lt;-<span class="st"> </span><span class="dv">1000000</span></a>
<a class="sourceLine" id="cb37-8" title="8"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="op">:</span><span class="dv">111</span>){</a>
<a class="sourceLine" id="cb37-9" title="9">  lm[i] =<span class="st"> </span>lm[i<span class="dv">-1</span>] <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span><span class="op">-</span>us_mx_mal_<span class="dv">2014</span>[i<span class="dv">-1</span>,<span class="dv">4</span>])</a>
<a class="sourceLine" id="cb37-10" title="10">                }</a>
<a class="sourceLine" id="cb37-11" title="11"><span class="kw">plot</span>(lf, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;yellow&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;age&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;l_x&quot;</span>,<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1000000</span>))</a>
<a class="sourceLine" id="cb37-12" title="12"><span class="kw">lines</span>(lm, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;orange&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;age&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;l_x&quot;</span>,<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1000000</span>))</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:LxMalFemDataFigs"></span>
<img src="LifeCon_files/figure-html/LxMalFemDataFigs-1.png" alt="Expected number at risk for the 2010-2014 U.S. Females (in yellow) and Males (in orange) data across all ages" width="576" />
<p class="caption">
Figure 2.14: Expected number at risk for the 2010-2014 U.S. Females (in yellow) and Males (in orange) data across all ages
</p>
</div>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" title="1">us_mx_fem_<span class="dv">2014</span><span class="op">$</span>lf &lt;-<span class="st"> </span>lf</a>
<a class="sourceLine" id="cb38-2" title="2">us_mx_mal_<span class="dv">2014</span><span class="op">$</span>lm &lt;-<span class="st"> </span>lm</a></code></pre></div>
<p><br></p>
<!-- ```{r, echo = FALSE, results = "asis"} -->
<!-- library(kableExtra) -->
<!-- options(kableExtra.html.bsTable = T) -->
<!-- tmp_life_table_us_mx_fem_2014 <- us_mx_fem_2014;  -->
<!-- colnames(tmp_life_table_us_mx_fem_2014)[c(4,5)]<- c("qx US Females","lx US Females") -->
<!-- rownames(tmp_life_table_us_mx_fem_2014) <- NULL -->
<!-- kbl(tmp_life_table_us_mx_fem_2014, escape = F,  -->
<!--       booktabs = TRUE, digits = 9) %>% -->
<!--   kable_styling(font_size = 9) %>% -->
<!--   scroll_box(width = "500px", height = "300px") -->
<!-- ``` -->
<div id="htmlwidget-022c21896016dcd5e78a" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-022c21896016dcd5e78a">{"x":{"filter":"none","data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111"],[2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110],[0.005461737,0.000379927,0.00022489,0.000169394,0.000138322,0.000119244,0.000105818,9.4484e-005,9.9099e-005,9.4716e-005,9.4384e-005,9.7954e-005,0.000110047,0.000125565,0.000151564,0.000179626,0.000230519,0.000269124,0.000321974,0.000362117,0.000387128,0.00042777,0.000446409,0.000461424,0.000487478,0.000508638,0.00054749,0.000549511,0.000595308,0.000634958,0.000668207,0.00070117,0.000747968,0.000787034,0.000846014,0.000916309,0.000964254,0.00102457,0.001107979,0.001189197,0.00128909,0.001402989,0.001549873,0.001683629,0.001849298,0.002011741,0.002248298,0.002442626,0.002676796,0.002956136,0.003215911,0.003507014,0.003785892,0.004022691,0.004360356,0.004669609,0.005022475,0.005389632,0.00572436,0.006102973,0.006578644,0.007094307,0.007691701,0.008375706,0.009132249,0.009926368,0.01081687,0.011807399,0.013002992,0.014262061,0.015712186,0.017165968,0.018739708,0.020420986,0.022628922,0.025042538,0.027750633,0.030759063,0.034071985,0.037903693,0.042329149,0.047007984,0.052498856,0.058315291,0.065539109,0.073797431,0.082574481,0.093398924,0.105567283,0.119743293,0.136610109,0.152626502,0.171825495,0.191587343,0.21591038,0.239354641,0.265723628,0.292275032,0.321674255,0.346587013,0.376656424,0.409128282,0.443580404,0.477090919,0.504199806,0.544747305,0.566723146,0.557618769,0.636754582,0.659418665,0.593688157],[0.005446849,0.000379855,0.000224865,0.00016938,0.000138313,0.000119237,0.000105813,9.4479e-005,9.9094e-005,9.4711e-005,9.4379e-005,9.7949e-005,0.000110041,0.000125557,0.000151552,0.00017961,0.000230492,0.000269087,0.000321922,0.000362051,0.000387053,0.000427678,0.00044631,0.000461317,0.000487359,0.000508508,0.000547341,0.00054936,0.000595131,0.000634756,0.000667984,0.000700924,0.000747689,0.000786725,0.000845656,0.00091589,0.00096379,0.001024046,0.001107365,0.00118849,0.001288259,0.001402006,0.001548672,0.001682212,0.001847589,0.002009718,0.002245773,0.002439646,0.002673216,0.002951771,0.003210746,0.003500871,0.003778734,0.004014611,0.004350863,0.004658723,0.005009883,0.005375134,0.005708007,0.006084388,0.006557052,0.007069201,0.007662195,0.008340727,0.009090677,0.009877264,0.010758578,0.011737965,0.012918819,0.01416084,0.015589394,0.017019472,0.018565211,0.02021389,0.022374808,0.024731575,0.027369122,0.030290816,0.033498071,0.037194339,0.041445778,0.04592022,0.051144593,0.05664753,0.063437582,0.071140167,0.079257143,0.089169924,0.100186071,0.112851855,0.127689734,0.141549709,0.157873884,0.174352492,0.194192485,0.212864318,0.233349021,0.253436821,0.275065705,0.29290271,0.313848222,0.335770982,0.358265366,0.379413896,0.39601131,0.420011675,0.432618378,0.427429135,0.470993512,0.482848115,0.447713396],[1000000,994553.151225326,994175.36542385,993951.810663968,993783.455585236,993646.002532917,993527.522841265,993422.395010789,993328.537021655,993230.104403902,993136.034143714,993042.302562327,992945.03527424,992835.770941365,992711.113242471,992560.665838855,992382.391655209,992153.654962591,991886.678953842,991567.368719675,991208.370340359,990824.719711805,990400.965493161,989958.939785607,989502.254546401,989020.011536961,988517.086673939,987976.031087407,987433.276168563,986845.623701882,986219.21734163,985560.439089276,984869.636209095,984133.260239908,983359.01825501,982527.434636199,981627.547766657,980681.465201927,979677.202649527,978592.341974964,977429.294615813,976170.112260438,974801.516338212,973291.868158373,971654.584463398,969859.366300027,967910.222141213,965736.515776742,963380.46090532,960805.136656105,957969.059937274,954893.26493812,951550.30633777,947954.650440596,944148.981049996,940041.118101349,935661.726727365,930974.170520104,925970.059993967,920684.616037427,915082.813515851,909082.56822127,902656.080526935,895739.753499331,888268.632635408,880193.669359774,871499.763951522,862123.666068536,852004.088715285,840997.202302176,829087.975547916,816162.996414872,802272.332977519,787377.977565693,771462.005595061,754200.691369053,735548.120372024,715416.814287228,693746.255080656,670507.093647945,645568.025626406,618811.956415475,590395.975374958,560200.413378874,528466.443887768,494941.810467076,459731.567544439,423294.557181951,385549.413527065,346922.732618068,307771.858661409,268472.551748404,230470.340248783,194085.092396369,160245.872781198,129127.328488559,101640.727767048,77922.963420286,58174.415303849,42172.628773675,29820.151520749,20461.149999342,13590.889569365,8721.744541887,5412.593461158,3269.145234705,1896.06606867,1075.793042404,615.967753357,325.850938148,168.514427013]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>Year_start<\/th>\n      <th>Age<\/th>\n      <th>mx US Females<\/th>\n      <th>qx US Females<\/th>\n      <th>lx US Females<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[1,2,3,4,5]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
<p><br></p>
<!-- ```{r, echo = TRUE} -->
<!-- tmp_life_table_us_mx_mal_2014 <- us_mx_mal_2014;  -->
<!-- colnames(tmp_life_table_us_mx_mal_2014)[c(4,5)]<- c("qx US Males","lx US Males") -->
<!-- rownames(tmp_life_table_us_mx_mal_2014) <- NULL -->
<!-- kable(tmp_life_table_us_mx_mal_2014, digits = 9, format.args = list(big.mark = ","), align = "ccrrr")  -->
<!-- ``` -->
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" title="1">tmp_life_table_us_mx_mal_<span class="dv">2014</span> &lt;-<span class="kw">round</span>(us_mx_mal_<span class="dv">2014</span>, <span class="dt">digits =</span> <span class="dv">9</span>); </a>
<a class="sourceLine" id="cb39-2" title="2"><span class="kw">colnames</span>(tmp_life_table_us_mx_mal_<span class="dv">2014</span>)[<span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">5</span>)]&lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;qx US Males&quot;</span>,<span class="st">&quot;lx US Males&quot;</span>)</a>
<a class="sourceLine" id="cb39-3" title="3"><span class="kw">rownames</span>(tmp_life_table_us_mx_mal_<span class="dv">2014</span>) &lt;-<span class="st"> </span><span class="ot">NULL</span></a>
<a class="sourceLine" id="cb39-4" title="4">DT<span class="op">::</span><span class="kw">datatable</span>(tmp_life_table_us_mx_mal_<span class="dv">2014</span>) </a></code></pre></div>
<div id="htmlwidget-6cb5f4fbf41c3e0a3a8a" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-6cb5f4fbf41c3e0a3a8a">{"x":{"filter":"none","data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111"],[2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110],[0.006554279,0.000441664,0.000298869,0.000225097,0.000184733,0.000145992,0.000126793,0.00012798,0.000123273,0.000124356,0.000116706,0.000133848,0.000148599,0.000184404,0.000240389,0.000319099,0.000465938,0.000615237,0.000871256,0.000999072,0.001080058,0.00121595,0.001281995,0.001286581,0.001321845,0.001326952,0.001364851,0.001360392,0.001391404,0.00143017,0.001444791,0.001499587,0.001504144,0.001556924,0.00161007,0.001643431,0.001707233,0.001778278,0.001856692,0.001987367,0.002120296,0.002276293,0.002453793,0.002622969,0.002861236,0.003149078,0.0035035,0.003891369,0.004254833,0.004669722,0.005147895,0.005603548,0.006102454,0.006632106,0.007159169,0.007858095,0.008507177,0.009117862,0.009847971,0.010525185,0.011292433,0.011996725,0.01285681,0.013639883,0.014602391,0.01552635,0.016854455,0.018142745,0.019870291,0.021486903,0.023501129,0.025437143,0.027755992,0.030132777,0.032863702,0.036117794,0.039656656,0.043706037,0.047988173,0.052732396,0.058697753,0.065032209,0.072275784,0.079376535,0.088448729,0.097701102,0.108732324,0.122047382,0.137403406,0.153935031,0.174568097,0.194076325,0.218380074,0.243922318,0.269914989,0.296257342,0.328711367,0.359188363,0.388741074,0.418796227,0.458783614,0.489988026,0.532025385,0.562926242,0.587131351,0.648959567,0.587329097,0.670120241,0.611534481,0.571037316,0.520304886],[0.006532847,0.000441567,0.000298824,0.000225072,0.000184715,0.000145981,0.000126785,0.000127971,0.000123266,0.000124348,0.0001167,0.000133839,0.000148588,0.000184387,0.00024036,0.000319048,0.000465829,0.000615048,0.000870877,0.000998573,0.001079475,0.001215211,0.001281174,0.001285754,0.001320971,0.001326072,0.00136392,0.001359468,0.001390437,0.001429147,0.001443748,0.001498463,0.001503013,0.001555713,0.001608775,0.001642082,0.001705777,0.001776698,0.001854969,0.001985393,0.00211805,0.002273704,0.002450785,0.002619532,0.002857147,0.003144125,0.00349737,0.003883807,0.004245794,0.004658836,0.005134667,0.005587877,0.006083872,0.006610162,0.007133603,0.007827301,0.008471094,0.00907642,0.009799639,0.010469989,0.011228913,0.011925051,0.012774515,0.013547281,0.014496293,0.015406438,0.016713213,0.017979156,0.019674178,0.021257704,0.023227128,0.025116344,0.027374333,0.029683311,0.032329558,0.035473329,0.038880623,0.042764692,0.04685494,0.051366163,0.057008258,0.062962718,0.069725695,0.076307943,0.084649959,0.09308006,0.103029517,0.114893571,0.128381461,0.142672281,0.160180337,0.176404959,0.196180127,0.216451501,0.236555607,0.256403955,0.28014924,0.301757184,0.322090224,0.342161769,0.367948003,0.38736627,0.412585975,0.430459989,0.444080262,0.477410787,0.444190182,0.488352947,0.457482253,0.435060886,0.405660685],[1000000,993467.153396667,993028.471573492,992731.730837713,992508.294772126,992324.963166681,992180.102089413,992054.308520238,991927.353874594,991805.083363008,991681.754540924,991566.025608219,991433.314947339,991285.999945372,991103.219911199,990864.998388369,990548.864611209,990087.43792825,989478.486716998,988616.772599574,987629.566618149,986563.444851582,985364.562100365,984102.138628773,982836.825438087,981538.5260364,980236.935231673,978899.970170733,977569.187436454,976209.939396637,974814.791441826,973407.404338503,971948.789278771,970487.937724452,968978.137278155,967419.269652184,965830.688197836,964183.196857733,962470.134487962,960684.781773021,958777.44451293,956746.705727984,954571.347086753,952231.898399321,949737.49613849,947023.956895774,944046.395561036,940744.715970938,937091.045044824,933112.349713461,928765.132285424,923996.232566058,918833.055345973,913242.992351659,907206.30799377,900734.658189527,893684.336955042,886113.853170157,878071.111360516,869466.331826384,860363.028921031,850702.087710603,840557.421929997,829819.70895027,818577.908043733,806711.563000393,794283.011616644,781007.990234875,766966.125677398,751876.697958741,735893.52546823,718800.832475826,700747.18320007,681564.696260369,661333.599320297,639952.976606812,617251.714273909,593252.583122589,567882.318846948,541274.227011839,513471.046712346,484198.956979158,453712.474503645,422077.057077706,389869.225038856,356866.811014566,323649.62683574,290304.162095146,256950.080364669,223962.453706224,192009.219523102,161253.118054731,132807.268333851,106753.121550447,83646.248179621,63859.259161857,47485.492548226,34182.467883393,23867.662634618,16180.121827663,10643.902725706,6727.4999743,4121.493399928,2421.023025957,1378.869480968,766.540760674,400.585932943,222.649594558,113.918008888,61.8025415,34.914673055]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>Year_start<\/th>\n      <th>Age<\/th>\n      <th>mx US Males<\/th>\n      <th>qx US Males<\/th>\n      <th>lx US Males<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[1,2,3,4,5]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
<p>We could use these life tables to obtain other death/survival related projections such as the newborn survival probabilities curves, which appears in Figure <a href="modeling-lifetimes.html#fig:P0USFemMalDataFigs">2.15</a>.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" title="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb40-2" title="2">kP0f &lt;-<span class="st"> </span>us_mx_fem_<span class="dv">2014</span><span class="op">$</span>lf<span class="op">/</span>us_mx_fem_<span class="dv">2014</span><span class="op">$</span>l[<span class="dv">1</span>]</a>
<a class="sourceLine" id="cb40-3" title="3"><span class="kw">plot</span>(kP0f, <span class="dt">xlab=</span><span class="st">&quot;age&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;green&quot;</span>)</a>
<a class="sourceLine" id="cb40-4" title="4">kP0m &lt;-<span class="st"> </span>us_mx_mal_<span class="dv">2014</span><span class="op">$</span>lm<span class="op">/</span>us_mx_mal_<span class="dv">2014</span><span class="op">$</span>l[<span class="dv">1</span>]</a>
<a class="sourceLine" id="cb40-5" title="5"><span class="kw">plot</span>(kP0m, <span class="dt">xlab=</span><span class="st">&quot;age&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;green&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:P0USFemMalDataFigs"></span>
<img src="LifeCon_files/figure-html/P0USFemMalDataFigs-1.png" alt="One year death probability curve for newborn Femals (left) and Males (right) for the 2010-2014 U.S. data across all ages" width="768" />
<p class="caption">
Figure 2.15: One year death probability curve for newborn Femals (left) and Males (right) for the 2010-2014 U.S. data across all ages
</p>
</div>
<p><span class="math inline">\(\color{red}{\text{[Vali:] I assume that the next calculation is based on the following integral aproximation $\stackrel{\circ}{e}_x\approx 0.5+e_x$?}}\)</span></p>
<p><span class="math inline">\(\color{red}{\text{[Vali:] Some calculations neeed the kurtate future lifetime $e_x$ which I thought that would be defined by Adam and Emil.}}\)</span></p>
<p><span class="math inline">\(\color{red}{\text{[Vali:] No changes are made in this subsection from this point.}}\)</span></p>
<p><span class="math inline">\(\color{red}{\text{[Vali:] The flow of the chapter is not ideal, especially the CF assumption.}}\)</span></p>
<p>Life expectancy:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" title="1"><span class="kw">sum</span>(kP0f) <span class="op">-</span><span class="st"> </span><span class="fl">0.5</span></a></code></pre></div>
<pre><code>## [1] 81.3014163</code></pre>
<p>And we can do the same for a 50-year old female:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" title="1">kP50 &lt;-<span class="st"> </span>us_mx_fem_<span class="dv">2014</span><span class="op">$</span>l[<span class="dv">51</span><span class="op">:</span><span class="dv">111</span>]<span class="op">/</span>us_mx_fem_<span class="dv">2014</span><span class="op">$</span>l[<span class="dv">51</span>]</a>
<a class="sourceLine" id="cb43-2" title="2"><span class="kw">plot</span>(kP50,<span class="dt">xlab=</span><span class="st">&quot;age&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)</a></code></pre></div>
<p><img src="LifeCon_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Let’s go through and evaluate period life expectancies at birth and at 50 across the years. This is a little more involved:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" title="1">e0 &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">16</span>)</a>
<a class="sourceLine" id="cb44-2" title="2">e50 &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">16</span>)</a>
<a class="sourceLine" id="cb44-3" title="3"></a>
<a class="sourceLine" id="cb44-4" title="4"><span class="kw">plot</span>(kP0f,<span class="dt">xlab=</span><span class="st">&quot;age&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">col =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb44-5" title="5"></a>
<a class="sourceLine" id="cb44-6" title="6">i &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb44-7" title="7"></a>
<a class="sourceLine" id="cb44-8" title="8"><span class="cf">for</span> (s <span class="cf">in</span> <span class="kw">seq</span>(<span class="dv">1935</span>,<span class="dv">2010</span>,<span class="dv">5</span>)){</a>
<a class="sourceLine" id="cb44-9" title="9">  <span class="co">#Get central death rates for each start yeat</span></a>
<a class="sourceLine" id="cb44-10" title="10">  mx &lt;-<span class="st"> </span>us_mx[us_mx<span class="op">$</span>Year_start <span class="op">==</span><span class="st"> </span>s,<span class="dv">4</span>]</a>
<a class="sourceLine" id="cb44-11" title="11">  s0 &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">111</span>)</a>
<a class="sourceLine" id="cb44-12" title="12">  </a>
<a class="sourceLine" id="cb44-13" title="13">  <span class="co">#Calculate the survival function</span></a>
<a class="sourceLine" id="cb44-14" title="14">  s0[<span class="dv">1</span>] &lt;-<span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb44-15" title="15">  <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">2</span><span class="op">:</span><span class="dv">111</span>){</a>
<a class="sourceLine" id="cb44-16" title="16">    s0[j] &lt;-<span class="st"> </span>s0[j<span class="dv">-1</span>]<span class="op">*</span><span class="kw">exp</span>(<span class="op">-</span>mx[j<span class="dv">-1</span>])</a>
<a class="sourceLine" id="cb44-17" title="17">  }</a>
<a class="sourceLine" id="cb44-18" title="18">  </a>
<a class="sourceLine" id="cb44-19" title="19">  <span class="co">#Include in the plot</span></a>
<a class="sourceLine" id="cb44-20" title="20">  <span class="kw">lines</span>(s0, <span class="dt">col=</span>(i<span class="op">+</span><span class="dv">1</span>))</a>
<a class="sourceLine" id="cb44-21" title="21">  </a>
<a class="sourceLine" id="cb44-22" title="22">  <span class="co">#And evaluate life expectancies by summing over kPx&#39;s</span></a>
<a class="sourceLine" id="cb44-23" title="23">  e0[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(s0)<span class="op">-</span><span class="fl">0.5</span></a>
<a class="sourceLine" id="cb44-24" title="24">  e50[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(s0[<span class="dv">51</span><span class="op">:</span><span class="dv">111</span>]<span class="op">/</span>s0[<span class="dv">51</span>])<span class="op">-</span><span class="fl">0.5</span></a>
<a class="sourceLine" id="cb44-25" title="25">  i &lt;-<span class="st"> </span>i<span class="op">+</span><span class="dv">1</span></a>
<a class="sourceLine" id="cb44-26" title="26">}</a></code></pre></div>
<p><img src="LifeCon_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>As is evident, the survival function has shifted quite dramatically over the past eighty years. The same is true for life expectancies:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" title="1"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</a>
<a class="sourceLine" id="cb45-2" title="2"><span class="kw">plot</span>(<span class="kw">seq</span>(<span class="dv">1935</span>,<span class="dv">2010</span>,<span class="dv">5</span>),e0, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">main=</span><span class="st">&quot;life expectancies at birth, across years&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;year&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;life expectancy&quot;</span>)</a>
<a class="sourceLine" id="cb45-3" title="3"><span class="kw">plot</span>(<span class="kw">seq</span>(<span class="dv">1935</span>,<span class="dv">2010</span>,<span class="dv">5</span>),e50, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">main=</span><span class="st">&quot;life expectancies at 50, across years&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;year&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;life expectancy&quot;</span>)</a></code></pre></div>
<p><img src="LifeCon_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
</div>
<div id="S:LifeTabMImpr" class="section level3">
<h3><span class="header-section-number">2.4.2</span> Mortality Improvement Modeling</h3>
<p><span class="math inline">\(\color{red}{\text{[Vali:] No changes are made in this subsection.}}\)</span></p>
<p>The fundamental issue e.g. when compiling a life table as we did here relying on one year of mortality data, we are relying on the snapshot of the year 2014 mortality experience. For a life insurance company selling annuities, in order to adequately price and reserve for their future liabilities, it is necessary to take into account future changes in mortality. As we have seen above, life expectancies have changed substantially over the last decades. This means that an eighty year old today may not have the same <span class="math inline">\(q_{80}\)</span> as an eighty year old twenty years from now, which is the relevant <span class="math inline">\(q_{80}\)</span> when selling an annuity to a sixty year old today…</p>
<p>One way of describing how mortality changed across years and ages are so-called <em>mortality improvement factors</em>, i.e. the percentage reduction in the mortality rate for each age <span class="math inline">\(x\)</span> over successive years (<span class="math inline">\(t-1\)</span> to <span class="math inline">\(t\)</span>):
<span class="math display">\[
\varphi(x,t) = 1 - \frac{q_x(t)}{q_x(t-1)}.
\]</span></p>
<p>Since we consider data in five-year intervals, we scale to one year:
<span class="math display">\[
\varphi(x,t) = 1 - \left(\frac{q_x(t)}{q_x(t-5)}\right)^{1/5}.
\]</span>
To obtain an impression, let’s evaluate in the context of our mortality data. One way of visualizing is a so-called heat map. As detailed in study note, patterns on the vertical, horizontal, and diagonal dimension relate to year, age, and cohort effects.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" title="1">us_mx_fem &lt;-<span class="st"> </span>us_mx[,<span class="op">-</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">6</span>)]</a>
<a class="sourceLine" id="cb46-2" title="2"><span class="kw">colnames</span>(us_mx_fem)[<span class="kw">colnames</span>(us_mx_fem)<span class="op">==</span><span class="st">&quot;Female&quot;</span>] &lt;-<span class="st"> &quot;mx&quot;</span></a>
<a class="sourceLine" id="cb46-3" title="3">us_mx_fem<span class="op">$</span>qx &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">-</span><span class="kw">exp</span>(<span class="op">-</span>us_mx_fem<span class="op">$</span>mx)</a>
<a class="sourceLine" id="cb46-4" title="4"></a>
<a class="sourceLine" id="cb46-5" title="5">phi &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">111</span><span class="op">*</span><span class="dv">15</span>),<span class="dt">nrow=</span><span class="dv">111</span>,<span class="dt">ncol=</span><span class="dv">15</span>,<span class="dt">byrow =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb46-6" title="6"><span class="cf">for</span> (t <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">15</span>){</a>
<a class="sourceLine" id="cb46-7" title="7">  <span class="cf">for</span> (x <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">111</span>){</a>
<a class="sourceLine" id="cb46-8" title="8">    phi[x,t] &lt;-<span class="st"> </span><span class="dv">1</span> <span class="op">-</span><span class="st"> </span>(us_mx_fem[t<span class="op">*</span><span class="dv">111</span><span class="op">+</span>x,<span class="dv">4</span>]<span class="op">/</span>us_mx_fem[(t<span class="dv">-1</span>)<span class="op">*</span><span class="dv">111</span><span class="op">+</span>x,<span class="dv">4</span>])<span class="op">^</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">5</span>)</a>
<a class="sourceLine" id="cb46-9" title="9">  }</a>
<a class="sourceLine" id="cb46-10" title="10">}</a>
<a class="sourceLine" id="cb46-11" title="11"><span class="kw">heatmap</span>(phi,<span class="dt">Colv =</span> <span class="ot">NA</span>,<span class="dt">Rowv =</span> <span class="ot">NA</span>)</a></code></pre></div>
<p><img src="LifeCon_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>Diagonals = cohort effects!</p>
<p>One simple way of forecasting mortality into the future are so-called <em>single factor mortality improvement models</em>, i.e. models where <span class="math inline">\(\varphi(x,t)\)</span> only depends on <span class="math inline">\(x\)</span> – let’s write <span class="math inline">\(\varphi_x\)</span>. With that, the above equation becomes:
<span class="math display">\[
q_x(t)= q_x(t-1)\times (1- \varphi_x),
\]</span>
or, generalizing:
<span class="math display">\[
q_x(t) = q_x(0)\times (1-\varphi_x)^t
\]</span></p>
<p>To obtain suitable improvement factors, let’s average across years under consideration:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" title="1">phi_x &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">111</span>)</a>
<a class="sourceLine" id="cb47-2" title="2"><span class="cf">for</span> (x <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">111</span>){</a>
<a class="sourceLine" id="cb47-3" title="3">  phi_x[x] &lt;-<span class="st"> </span><span class="kw">mean</span>(phi[x,])</a>
<a class="sourceLine" id="cb47-4" title="4">}</a></code></pre></div>
<p>And let’s plot to check them out, and include smoothed version:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" title="1">ages &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">111</span></a>
<a class="sourceLine" id="cb48-2" title="2">lo &lt;-<span class="st"> </span><span class="kw">loess</span>(phi_x <span class="op">~</span><span class="st"> </span>ages)</a>
<a class="sourceLine" id="cb48-3" title="3"><span class="kw">plot</span>(phi_x, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">main=</span><span class="st">&quot;mortality improvement factors&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;age&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;phi&quot;</span>)</a>
<a class="sourceLine" id="cb48-4" title="4"><span class="kw">lines</span>(<span class="kw">predict</span>(lo), <span class="dt">col=</span><span class="st">&#39;blue&#39;</span>, <span class="dt">lwd=</span><span class="dv">2</span>)</a></code></pre></div>
<p><img src="LifeCon_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" title="1">phi_x &lt;-<span class="st"> </span><span class="kw">predict</span>(lo)</a></code></pre></div>
<p>Using smoothed.</p>
<p>We can get a life table for a sixty year old in 2015 by applying the improvement factors to forecast future mortality probabilities using the relationship above:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" title="1">q_50plusx &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">61</span>)</a>
<a class="sourceLine" id="cb50-2" title="2"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">61</span>){</a>
<a class="sourceLine" id="cb50-3" title="3">q_50plusx[i] &lt;-<span class="st"> </span>us_mx_fem_<span class="dv">2014</span>[<span class="dv">50</span><span class="op">+</span>i,<span class="dv">4</span>] <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>phi_x[<span class="dv">50</span><span class="op">+</span>i])<span class="op">^</span>(i<span class="dv">-1</span>)</a>
<a class="sourceLine" id="cb50-4" title="4">}</a></code></pre></div>
<p>And let’s compare the resulting <span class="math inline">\(q_x\)</span>, the ones for 2015 across all ages above 60 and the forecasted cohort mortalities for the 60 year old in 2015:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" title="1"><span class="kw">plot</span>(q_50plusx, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">main=</span><span class="st">&quot;q_x comparison&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;age&quot;</span>)</a>
<a class="sourceLine" id="cb51-2" title="2"><span class="kw">lines</span>(us_mx_fem_<span class="dv">2014</span>[<span class="dv">51</span><span class="op">:</span><span class="dv">111</span>,<span class="dv">4</span>], <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">lwd =</span> <span class="dv">2</span>)</a></code></pre></div>
<p><img src="LifeCon_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>Evaluate life expectancy at 50:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" title="1">kP50_i &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">61</span>)</a>
<a class="sourceLine" id="cb52-2" title="2">kP50_i[<span class="dv">1</span>] &lt;-<span class="st"> </span><span class="dv">1</span> </a>
<a class="sourceLine" id="cb52-3" title="3"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="op">:</span><span class="dv">61</span>){</a>
<a class="sourceLine" id="cb52-4" title="4">  kP50_i[i] &lt;-<span class="st"> </span>kP50_i[i<span class="dv">-1</span>] <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>q_50plusx[i<span class="dv">-1</span>])</a>
<a class="sourceLine" id="cb52-5" title="5">}</a>
<a class="sourceLine" id="cb52-6" title="6"></a>
<a class="sourceLine" id="cb52-7" title="7"><span class="kw">plot</span>(kP50,<span class="dt">xlab=</span><span class="st">&quot;age&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">lwd =</span> <span class="dv">5</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)</a>
<a class="sourceLine" id="cb52-8" title="8"><span class="kw">lines</span>(kP50_i, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">lwd =</span> <span class="dv">2</span>)</a></code></pre></div>
<p><img src="LifeCon_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" title="1"><span class="kw">sum</span>(kP50) <span class="op">-</span><span class="st"> </span><span class="fl">0.5</span></a></code></pre></div>
<pre><code>## [1] 33.4390951</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" title="1"><span class="kw">sum</span>(kP50_i) <span class="op">-</span><span class="st"> </span><span class="fl">0.5</span></a></code></pre></div>
<pre><code>## [1] 35.7433033</code></pre>
</div>
</div>
<div id="non-parametric-survival-estimation" class="section level2">
<h2><span class="header-section-number">2.5</span> Non-parametric survival estimation</h2>
<p>Kaplan-Meier and Nelson-Aalen. Please check out the <a href="https://ewfrees.github.io/Loss-Data-Analytics/C-ModelSelection.html#nonparametric-estimation-using-modified-data">Loss Data Analysis descriptions</a> of these topics.</p>
</div>
<div id="conditional-models-survival-regression" class="section level2">
<h2><span class="header-section-number">2.6</span> Conditional models: Survival regression</h2>
<p>parametric models; proportional hazard (Cox) model; additive model</p>
<ul>
<li>R tutorial – survival regression; constructing conditional mortality tables</li>
</ul>
<p><span class="math inline">\(\color{red}{\text{[Vali:] This is too far from my comfort zone and it would take some time to contribute.}}\)</span></p>

</div>
<div id="appendix-2a.-life-table-recursive-calculations" class="section level2 unnumbered">
<h2>Appendix 2A. Life Table: Recursive Calculations</h2>
<p>Actuaries and other analysts have found <em>life tables</em> to be useful in interpreting mortality patterns for many years. Origins of life tables can be traced back to Edmund Halley’s paper entitled, “An estimate of the degrees of the mortality of mankind, drawn from various tables of births and funerals in the city of Breslau,” published in 1693. Some scholars attribute this paper as marking the birth of actuarial science.</p>
<p>As introduced in <em>Section 2.4</em>, a life table is based on the quantities <span class="math inline">\(l_x = radix \times S_a(x)\)</span> where <span class="math inline">\(S_a(\cdot)\)</span> is the survival function for a life aged <span class="math inline">\(a\)</span>. In this expression, <span class="math inline">\(a\)</span> is the starting age of the table and <span class="math inline">\(radix\)</span> is a constant generally taken so that <span class="math inline">\(l_a\)</span> is a large round number. With this choice, we interpret <span class="math inline">\(l_x\)</span> to be the “number living” at age <span class="math inline">\(x\)</span>.</p>
<p><a href="#tab:2A1">Table 2A.1</a> shows life tables for female and male Indonesians. Here, each radix, one for females and one for males, is chosen so that there are 100,000 people alive at age <span class="math inline">\(a=20\)</span>. Also from <a href="#tab:2A1">Table 2A.1</a>, you will see that the mortality distribution is given in terms of (integral) values of <span class="math inline">\(x\)</span>; such a choice is common in life tables as is other regular successive values, e.g., quinquennial for five year values.</p>
<p>With a table of successive values, many interesting recursive expressions are available. To begin, we can define the change <span class="math inline">\(d_x = l_x - l_{x+1}\)</span> that we interpret as the “number dying” between ages <span class="math inline">\(x\)</span> and <span class="math inline">\(x+1\)</span>. These changes allow us to express life table quantities <span class="math inline">\(l_x\)</span> and <span class="math inline">\(d_x\)</span> in terms of one-year death rates, <span class="math inline">\(q_x\)</span>, as follows. Recall that <span class="math inline">\(q_x = 1 - S_0(x+1)/S_0(x) = 1 - S_a(x+1)/S_a(x)\)</span> and so</p>
<p><span class="math display">\[
\frac{d_x}{l_x} = \frac{l_x - l_{x+1}}{l_x} = \frac{radix}{radix}\frac{S_a(x) - S_a(x+1)}{S_a(x)} = q_x .
\]</span></p>
<p>From this we can use life table quantities <span class="math inline">\(l_x\)</span> and <span class="math inline">\(d_x\)</span> to calculate one-year death rates, <span class="math inline">\(q_x\)</span>. We can also reverse the process. That is,
starting with one-year death rates as inputs, we can calculate life table entries recursively using <span class="math inline">\(l_{x+1} = l_x - l_x q_x = l_x p_x\)</span> for <span class="math inline">\(x=a, a+1, \ldots\)</span>. Thus, for example, in <a href="#tab:2A1">Table 2A.1</a>, with <span class="math inline">\(x=20\)</span>, we have <span class="math inline">\(l_{21} = l_{20} - l_{20} q_{20} = (100000)(1 - 0.000340) = 99966\)</span>. For readers familiar with spreadsheet methods, click on a few cells in <a href="#tab:2A1">Table 2A.1</a> to see the recursive definition of table entries.</p>
<p>Later chapters on life contingent benefits will highlight recursive calculations. To foreshadow this, consider the curtate life expectancy introduced in <em>Section 2.4</em>. An easy calculation (that the reader should verify) shows the recursive expression</p>
<p><span class="math display">\[
e_x = \sum_{k=1}^{\infty} ~ {~}_k p_x 
= p_x (1 + e_{x+1}) .
\]</span></p>
<p>The <span class="math inline">\(e_x\)</span> columns in <a href="#tab:2A1">Table 2A.1</a> utilize this relationship. To visualize these entries, Figure <a href="modeling-lifetimes.html#fig:IndonesianLifeTablePlot">2.16</a> compares female to male life expectancies for the Indonesian data. Here, we see that females have a higher life expectancy at each age. The difference is greatest at the first age of the table <span class="math inline">\(a=20\)</span> which is 61.06 - 55.46 = 5.60.</p>
<p><strong>On Your Own.</strong> The Indonesian mortality data were retrieved from the <a href="https://mort.soa.org">Mortality and Other Rate Tables</a> database sponsored by the Society of Actuaries. This database contains mortality (and other) rates from scores of countries. You will enjoy downloading them and comparing mortality experiences across the globe.</p>
<p><a id=tab:2A1></a></p>
<p>Table 2A.1. <strong>Indonesian Life Table</strong></p>
<div id="spreadsheetLC2A1">

</div>
<p>
<button id="downloadLC2A1">
Export this spreadsheet as CSV
</button>
</p>
<script>var data2A1 = [{"V1":20,"V2":0.00034,"V3":"100000","V4":"=C1*B1","V5":"=(1-B1)*(1+E2)","V6":0.000947,"V7":"100000","V8":"=G1*F1","V9":"=(1-F1)*(1+I2)"},{"V1":21,"V2":0.000329,"V3":"=C1-D1","V4":"=C2*B2","V5":"=(1-B2)*(1+E3)","V6":0.000895,"V7":"=G1-H1","V8":"=G2*F2","V9":"=(1-F2)*(1+I3)"},{"V1":22,"V2":0.000323,"V3":"=C2-D2","V4":"=C3*B3","V5":"=(1-B3)*(1+E4)","V6":0.000846,"V7":"=G2-H2","V8":"=G3*F3","V9":"=(1-F3)*(1+I4)"},{"V1":23,"V2":0.000328,"V3":"=C3-D3","V4":"=C4*B4","V5":"=(1-B4)*(1+E5)","V6":0.000802,"V7":"=G3-H3","V8":"=G4*F4","V9":"=(1-F4)*(1+I5)"},{"V1":24,"V2":0.000342,"V3":"=C4-D4","V4":"=C5*B5","V5":"=(1-B5)*(1+E6)","V6":0.000762,"V7":"=G4-H4","V8":"=G5*F5","V9":"=(1-F5)*(1+I6)"},{"V1":25,"V2":0.000361,"V3":"=C5-D5","V4":"=C6*B6","V5":"=(1-B6)*(1+E7)","V6":0.000727,"V7":"=G5-H5","V8":"=G6*F6","V9":"=(1-F6)*(1+I7)"},{"V1":26,"V2":0.000376,"V3":"=C6-D6","V4":"=C7*B7","V5":"=(1-B7)*(1+E8)","V6":0.000697,"V7":"=G6-H6","V8":"=G7*F7","V9":"=(1-F7)*(1+I8)"},{"V1":27,"V2":0.000389,"V3":"=C7-D7","V4":"=C8*B8","V5":"=(1-B8)*(1+E9)","V6":0.000674,"V7":"=G7-H7","V8":"=G8*F8","V9":"=(1-F8)*(1+I9)"},{"V1":28,"V2":0.000397,"V3":"=C8-D8","V4":"=C9*B9","V5":"=(1-B9)*(1+E10)","V6":0.000657,"V7":"=G8-H8","V8":"=G9*F9","V9":"=(1-F9)*(1+I10)"},{"V1":29,"V2":0.000401,"V3":"=C9-D9","V4":"=C10*B10","V5":"=(1-B10)*(1+E11)","V6":0.000647,"V7":"=G9-H9","V8":"=G10*F10","V9":"=(1-F10)*(1+I11)"},{"V1":30,"V2":0.000409,"V3":"=C10-D10","V4":"=C11*B11","V5":"=(1-B11)*(1+E12)","V6":0.000646,"V7":"=G10-H10","V8":"=G11*F11","V9":"=(1-F11)*(1+I12)"},{"V1":31,"V2":0.000424,"V3":"=C11-D11","V4":"=C12*B12","V5":"=(1-B12)*(1+E13)","V6":0.000652,"V7":"=G11-H11","V8":"=G12*F12","V9":"=(1-F12)*(1+I13)"},{"V1":32,"V2":0.000446,"V3":"=C12-D12","V4":"=C13*B13","V5":"=(1-B13)*(1+E14)","V6":0.000669,"V7":"=G12-H12","V8":"=G13*F13","V9":"=(1-F13)*(1+I14)"},{"V1":33,"V2":0.000475,"V3":"=C13-D13","V4":"=C14*B14","V5":"=(1-B14)*(1+E15)","V6":0.000696,"V7":"=G13-H13","V8":"=G14*F14","V9":"=(1-F14)*(1+I15)"},{"V1":34,"V2":0.000513,"V3":"=C14-D14","V4":"=C15*B15","V5":"=(1-B15)*(1+E16)","V6":0.000734,"V7":"=G14-H14","V8":"=G15*F15","V9":"=(1-F15)*(1+I16)"},{"V1":35,"V2":0.000561,"V3":"=C15-D15","V4":"=C16*B16","V5":"=(1-B16)*(1+E17)","V6":0.000784,"V7":"=G15-H15","V8":"=G16*F16","V9":"=(1-F16)*(1+I17)"},{"V1":36,"V2":0.000619,"V3":"=C16-D16","V4":"=C17*B17","V5":"=(1-B17)*(1+E18)","V6":0.000849,"V7":"=G16-H16","V8":"=G17*F17","V9":"=(1-F17)*(1+I18)"},{"V1":37,"V2":0.000689,"V3":"=C17-D17","V4":"=C18*B18","V5":"=(1-B18)*(1+E19)","V6":0.000928,"V7":"=G17-H17","V8":"=G18*F18","V9":"=(1-F18)*(1+I19)"},{"V1":38,"V2":0.000771,"V3":"=C18-D18","V4":"=C19*B19","V5":"=(1-B19)*(1+E20)","V6":0.001024,"V7":"=G18-H18","V8":"=G19*F19","V9":"=(1-F19)*(1+I20)"},{"V1":39,"V2":0.000865,"V3":"=C19-D19","V4":"=C20*B20","V5":"=(1-B20)*(1+E21)","V6":0.001137,"V7":"=G19-H19","V8":"=G20*F20","V9":"=(1-F20)*(1+I21)"},{"V1":40,"V2":0.000972,"V3":"=C20-D20","V4":"=C21*B21","V5":"=(1-B21)*(1+E22)","V6":0.001271,"V7":"=G20-H20","V8":"=G21*F21","V9":"=(1-F21)*(1+I22)"},{"V1":41,"V2":0.001092,"V3":"=C21-D21","V4":"=C22*B22","V5":"=(1-B22)*(1+E23)","V6":0.001426,"V7":"=G21-H21","V8":"=G22*F22","V9":"=(1-F22)*(1+I23)"},{"V1":42,"V2":0.001224,"V3":"=C22-D22","V4":"=C23*B23","V5":"=(1-B23)*(1+E24)","V6":0.001605,"V7":"=G22-H22","V8":"=G23*F23","V9":"=(1-F23)*(1+I24)"},{"V1":43,"V2":0.001367,"V3":"=C23-D23","V4":"=C24*B24","V5":"=(1-B24)*(1+E25)","V6":0.001809,"V7":"=G23-H23","V8":"=G24*F24","V9":"=(1-F24)*(1+I25)"},{"V1":44,"V2":0.001521,"V3":"=C24-D24","V4":"=C25*B25","V5":"=(1-B25)*(1+E26)","V6":0.002043,"V7":"=G24-H24","V8":"=G25*F25","V9":"=(1-F25)*(1+I26)"},{"V1":45,"V2":0.001686,"V3":"=C25-D25","V4":"=C26*B26","V5":"=(1-B26)*(1+E27)","V6":0.002307,"V7":"=G25-H25","V8":"=G26*F26","V9":"=(1-F26)*(1+I27)"},{"V1":46,"V2":0.001859,"V3":"=C26-D26","V4":"=C27*B27","V5":"=(1-B27)*(1+E28)","V6":0.002605,"V7":"=G26-H26","V8":"=G27*F27","V9":"=(1-F27)*(1+I28)"},{"V1":47,"V2":0.002042,"V3":"=C27-D27","V4":"=C28*B28","V5":"=(1-B28)*(1+E29)","V6":0.002941,"V7":"=G27-H27","V8":"=G28*F28","V9":"=(1-F28)*(1+I29)"},{"V1":48,"V2":0.002233,"V3":"=C28-D28","V4":"=C29*B29","V5":"=(1-B29)*(1+E30)","V6":0.003318,"V7":"=G28-H28","V8":"=G29*F29","V9":"=(1-F29)*(1+I30)"},{"V1":49,"V2":0.002434,"V3":"=C29-D29","V4":"=C30*B30","V5":"=(1-B30)*(1+E31)","V6":0.003739,"V7":"=G29-H29","V8":"=G30*F30","V9":"=(1-F30)*(1+I31)"},{"V1":50,"V2":0.002645,"V3":"=C30-D30","V4":"=C31*B31","V5":"=(1-B31)*(1+E32)","V6":0.004209,"V7":"=G30-H30","V8":"=G31*F31","V9":"=(1-F31)*(1+I32)"},{"V1":51,"V2":0.002868,"V3":"=C31-D31","V4":"=C32*B32","V5":"=(1-B32)*(1+E33)","V6":0.004733,"V7":"=G31-H31","V8":"=G32*F32","V9":"=(1-F32)*(1+I33)"},{"V1":52,"V2":0.003105,"V3":"=C32-D32","V4":"=C33*B33","V5":"=(1-B33)*(1+E34)","V6":0.005319,"V7":"=G32-H32","V8":"=G33*F33","V9":"=(1-F33)*(1+I34)"},{"V1":53,"V2":0.003358,"V3":"=C33-D33","V4":"=C34*B34","V5":"=(1-B34)*(1+E35)","V6":0.005988,"V7":"=G33-H33","V8":"=G34*F34","V9":"=(1-F34)*(1+I35)"},{"V1":54,"V2":0.003629,"V3":"=C34-D34","V4":"=C35*B35","V5":"=(1-B35)*(1+E36)","V6":0.006761,"V7":"=G34-H34","V8":"=G35*F35","V9":"=(1-F35)*(1+I36)"},{"V1":55,"V2":0.003929,"V3":"=C35-D35","V4":"=C36*B36","V5":"=(1-B36)*(1+E37)","V6":0.007647,"V7":"=G35-H35","V8":"=G36*F36","V9":"=(1-F36)*(1+I37)"},{"V1":56,"V2":0.00427,"V3":"=C36-D36","V4":"=C37*B37","V5":"=(1-B37)*(1+E38)","V6":0.008648,"V7":"=G36-H36","V8":"=G37*F37","V9":"=(1-F37)*(1+I38)"},{"V1":57,"V2":0.004667,"V3":"=C37-D37","V4":"=C38*B38","V5":"=(1-B38)*(1+E39)","V6":0.009759,"V7":"=G37-H37","V8":"=G38*F38","V9":"=(1-F38)*(1+I39)"},{"V1":58,"V2":0.005132,"V3":"=C38-D38","V4":"=C39*B39","V5":"=(1-B39)*(1+E40)","V6":0.010971,"V7":"=G38-H38","V8":"=G39*F39","V9":"=(1-F39)*(1+I40)"},{"V1":59,"V2":0.005674,"V3":"=C39-D39","V4":"=C40*B40","V5":"=(1-B40)*(1+E41)","V6":0.012274,"V7":"=G39-H39","V8":"=G40*F40","V9":"=(1-F40)*(1+I41)"},{"V1":60,"V2":0.006301,"V3":"=C40-D40","V4":"=C41*B41","V5":"=(1-B41)*(1+E42)","V6":0.013657,"V7":"=G40-H40","V8":"=G41*F41","V9":"=(1-F41)*(1+I42)"},{"V1":61,"V2":0.007014,"V3":"=C41-D41","V4":"=C42*B42","V5":"=(1-B42)*(1+E43)","V6":0.015116,"V7":"=G41-H41","V8":"=G42*F42","V9":"=(1-F42)*(1+I43)"},{"V1":62,"V2":0.007813,"V3":"=C42-D42","V4":"=C43*B43","V5":"=(1-B43)*(1+E44)","V6":0.016652,"V7":"=G42-H42","V8":"=G43*F43","V9":"=(1-F43)*(1+I44)"},{"V1":63,"V2":0.008697,"V3":"=C43-D43","V4":"=C44*B44","V5":"=(1-B44)*(1+E45)","V6":0.018274,"V7":"=G43-H43","V8":"=G44*F44","V9":"=(1-F44)*(1+I45)"},{"V1":64,"V2":0.009669,"V3":"=C44-D44","V4":"=C45*B45","V5":"=(1-B45)*(1+E46)","V6":0.019999,"V7":"=G44-H44","V8":"=G45*F45","V9":"=(1-F45)*(1+I46)"},{"V1":65,"V2":0.010737,"V3":"=C45-D45","V4":"=C46*B46","V5":"=(1-B46)*(1+E47)","V6":0.021853,"V7":"=G45-H45","V8":"=G46*F46","V9":"=(1-F46)*(1+I47)"},{"V1":66,"V2":0.011915,"V3":"=C46-D46","V4":"=C47*B47","V5":"=(1-B47)*(1+E48)","V6":0.023862,"V7":"=G46-H46","V8":"=G47*F47","V9":"=(1-F47)*(1+I48)"},{"V1":67,"V2":0.01322,"V3":"=C47-D47","V4":"=C48*B48","V5":"=(1-B48)*(1+E49)","V6":0.026049,"V7":"=G47-H47","V8":"=G48*F48","V9":"=(1-F48)*(1+I49)"},{"V1":68,"V2":0.014665,"V3":"=C48-D48","V4":"=C49*B49","V5":"=(1-B49)*(1+E50)","V6":0.028432,"V7":"=G48-H48","V8":"=G49*F49","V9":"=(1-F49)*(1+I50)"},{"V1":69,"V2":0.016265,"V3":"=C49-D49","V4":"=C50*B50","V5":"=(1-B50)*(1+E51)","V6":0.031025,"V7":"=G49-H49","V8":"=G50*F50","V9":"=(1-F50)*(1+I51)"},{"V1":70,"V2":0.018037,"V3":"=C50-D50","V4":"=C51*B51","V5":"=(1-B51)*(1+E52)","V6":0.033846,"V7":"=G50-H50","V8":"=G51*F51","V9":"=(1-F51)*(1+I52)"},{"V1":71,"V2":0.019998,"V3":"=C51-D51","V4":"=C52*B52","V5":"=(1-B52)*(1+E53)","V6":0.036914,"V7":"=G51-H51","V8":"=G52*F52","V9":"=(1-F52)*(1+I53)"},{"V1":72,"V2":0.022167,"V3":"=C52-D52","V4":"=C53*B53","V5":"=(1-B53)*(1+E54)","V6":0.040249,"V7":"=G52-H52","V8":"=G53*F53","V9":"=(1-F53)*(1+I54)"},{"V1":73,"V2":0.024566,"V3":"=C53-D53","V4":"=C54*B54","V5":"=(1-B54)*(1+E55)","V6":0.043871,"V7":"=G53-H53","V8":"=G54*F54","V9":"=(1-F54)*(1+I55)"},{"V1":74,"V2":0.027217,"V3":"=C54-D54","V4":"=C55*B55","V5":"=(1-B55)*(1+E56)","V6":0.047803,"V7":"=G54-H54","V8":"=G55*F55","V9":"=(1-F55)*(1+I56)"},{"V1":75,"V2":0.030145,"V3":"=C55-D55","V4":"=C56*B56","V5":"=(1-B56)*(1+E57)","V6":0.052068,"V7":"=G55-H55","V8":"=G56*F56","V9":"=(1-F56)*(1+I57)"},{"V1":76,"V2":0.033377,"V3":"=C56-D56","V4":"=C57*B57","V5":"=(1-B57)*(1+E58)","V6":0.056691,"V7":"=G56-H56","V8":"=G57*F57","V9":"=(1-F57)*(1+I58)"},{"V1":77,"V2":0.036943,"V3":"=C57-D57","V4":"=C58*B58","V5":"=(1-B58)*(1+E59)","V6":0.061697,"V7":"=G57-H57","V8":"=G58*F58","V9":"=(1-F58)*(1+I59)"},{"V1":78,"V2":0.040874,"V3":"=C58-D58","V4":"=C59*B59","V5":"=(1-B59)*(1+E60)","V6":0.067115,"V7":"=G58-H58","V8":"=G59*F59","V9":"=(1-F59)*(1+I60)"},{"V1":79,"V2":0.045203,"V3":"=C59-D59","V4":"=C60*B60","V5":"=(1-B60)*(1+E61)","V6":0.072971,"V7":"=G59-H59","V8":"=G60*F60","V9":"=(1-F60)*(1+I61)"},{"V1":80,"V2":0.049967,"V3":"=C60-D60","V4":"=C61*B61","V5":"=(1-B61)*(1+E62)","V6":0.079295,"V7":"=G60-H60","V8":"=G61*F61","V9":"=(1-F61)*(1+I62)"},{"V1":81,"V2":0.055204,"V3":"=C61-D61","V4":"=C62*B62","V5":"=(1-B62)*(1+E63)","V6":0.086115,"V7":"=G61-H61","V8":"=G62*F62","V9":"=(1-F62)*(1+I63)"},{"V1":82,"V2":0.060955,"V3":"=C62-D62","V4":"=C63*B63","V5":"=(1-B63)*(1+E64)","V6":0.093463,"V7":"=G62-H62","V8":"=G63*F63","V9":"=(1-F63)*(1+I64)"},{"V1":83,"V2":0.067262,"V3":"=C63-D63","V4":"=C64*B64","V5":"=(1-B64)*(1+E65)","V6":0.101369,"V7":"=G63-H63","V8":"=G64*F64","V9":"=(1-F64)*(1+I65)"},{"V1":84,"V2":0.07417,"V3":"=C64-D64","V4":"=C65*B65","V5":"=(1-B65)*(1+E66)","V6":0.109861,"V7":"=G64-H64","V8":"=G65*F65","V9":"=(1-F65)*(1+I66)"},{"V1":85,"V2":0.081726,"V3":"=C65-D65","V4":"=C66*B66","V5":"=(1-B66)*(1+E67)","V6":0.118972,"V7":"=G65-H65","V8":"=G66*F66","V9":"=(1-F66)*(1+I67)"},{"V1":86,"V2":0.089976,"V3":"=C66-D66","V4":"=C67*B67","V5":"=(1-B67)*(1+E68)","V6":0.128728,"V7":"=G66-H66","V8":"=G67*F67","V9":"=(1-F67)*(1+I68)"},{"V1":87,"V2":0.09897,"V3":"=C67-D67","V4":"=C68*B68","V5":"=(1-B68)*(1+E69)","V6":0.139159,"V7":"=G67-H67","V8":"=G68*F68","V9":"=(1-F68)*(1+I69)"},{"V1":88,"V2":0.108755,"V3":"=C68-D68","V4":"=C69*B69","V5":"=(1-B69)*(1+E70)","V6":0.150288,"V7":"=G68-H68","V8":"=G69*F69","V9":"=(1-F69)*(1+I70)"},{"V1":89,"V2":0.119379,"V3":"=C69-D69","V4":"=C70*B70","V5":"=(1-B70)*(1+E71)","V6":0.16214,"V7":"=G69-H69","V8":"=G70*F70","V9":"=(1-F70)*(1+I71)"},{"V1":90,"V2":0.130889,"V3":"=C70-D70","V4":"=C71*B71","V5":"=(1-B71)*(1+E72)","V6":0.174735,"V7":"=G70-H70","V8":"=G71*F71","V9":"=(1-F71)*(1+I72)"},{"V1":91,"V2":0.143328,"V3":"=C71-D71","V4":"=C72*B72","V5":"=(1-B72)*(1+E73)","V6":0.188088,"V7":"=G71-H71","V8":"=G72*F72","V9":"=(1-F72)*(1+I73)"},{"V1":92,"V2":0.156736,"V3":"=C72-D72","V4":"=C73*B73","V5":"=(1-B73)*(1+E74)","V6":0.202211,"V7":"=G72-H72","V8":"=G73*F73","V9":"=(1-F73)*(1+I74)"},{"V1":93,"V2":0.171147,"V3":"=C73-D73","V4":"=C74*B74","V5":"=(1-B74)*(1+E75)","V6":0.217112,"V7":"=G73-H73","V8":"=G74*F74","V9":"=(1-F74)*(1+I75)"},{"V1":94,"V2":0.186591,"V3":"=C74-D74","V4":"=C75*B75","V5":"=(1-B75)*(1+E76)","V6":0.23279,"V7":"=G74-H74","V8":"=G75*F75","V9":"=(1-F75)*(1+I76)"},{"V1":95,"V2":0.203086,"V3":"=C75-D75","V4":"=C76*B76","V5":"=(1-B76)*(1+E77)","V6":0.24924,"V7":"=G75-H75","V8":"=G76*F76","V9":"=(1-F76)*(1+I77)"},{"V1":96,"V2":0.220644,"V3":"=C76-D76","V4":"=C77*B77","V5":"=(1-B77)*(1+E78)","V6":0.266449,"V7":"=G76-H76","V8":"=G77*F77","V9":"=(1-F77)*(1+I78)"},{"V1":97,"V2":0.239265,"V3":"=C77-D77","V4":"=C78*B78","V5":"=(1-B78)*(1+E79)","V6":0.284395,"V7":"=G77-H77","V8":"=G78*F78","V9":"=(1-F78)*(1+I79)"},{"V1":98,"V2":0.258935,"V3":"=C78-D78","V4":"=C79*B79","V5":"=(1-B79)*(1+E80)","V6":0.303051,"V7":"=G78-H78","V8":"=G79*F79","V9":"=(1-F79)*(1+I80)"},{"V1":99,"V2":0.279627,"V3":"=C79-D79","V4":"=C80*B80","V5":"=(1-B80)*(1+E81)","V6":0.32238,"V7":"=G79-H79","V8":"=G80*F80","V9":"=(1-F80)*(1+I81)"},{"V1":100,"V2":0.301301,"V3":"=C80-D80","V4":"=C81*B81","V5":"=(1-B81)*(1+E82)","V6":0.342336,"V7":"=G80-H80","V8":"=G81*F81","V9":"=(1-F81)*(1+I82)"},{"V1":101,"V2":0.323899,"V3":"=C81-D81","V4":"=C82*B82","V5":"=(1-B82)*(1+E83)","V6":0.362865,"V7":"=G81-H81","V8":"=G82*F82","V9":"=(1-F82)*(1+I83)"},{"V1":102,"V2":0.34735,"V3":"=C82-D82","V4":"=C83*B83","V5":"=(1-B83)*(1+0)","V6":0.383907,"V7":"=G82-H82","V8":"=G83*F83","V9":"=(1-F83)*(1+0)"}];</script>
<script type="text/javascript">
// Spreadsheet Defined
var mySpreadsheet2A1 = jexcel(document.getElementById('spreadsheetLC2A1'), {
    data: data2A1,
    columns: [
       { type: 'text', width:'60', title: 'Age' },
       { type: 'numeric',  width:'140', mask: '#.000000', decimal:'.', title: 'Female \\(q\_x\\)'},
       { type: 'numeric',  width:'120', mask:'#.00', decimal:'.', title: 'Female \\(l\_x\\)'},
       { type: 'numeric',  width:'120', mask:'#.00', decimal:'.', title: 'Female \\(d\_x\\)'},
       { type: 'numeric',  width:'120', mask:'#.00', decimal:'.', title: 'Female \\(e\_x\\)'},
       { type: 'numeric',  width:'140', mask:' #.000000', decimal:'.', title: 'Male \\(q\_x\\)'},
       { type: 'numeric',  width:'120', mask:'#.00', decimal:'.', title: 'Male \\(l\_x\\)'},
       { type: 'numeric',  width:'120', mask:'#.00', decimal:'.', title: 'Male \\(d\_x\\)'},
       { type: 'numeric',  width:'120', mask:'#.00', decimal:'.', title: 'Male \\(e\_x\\)'},
        ],
    minDimensions: [9,13],
    tableOverflow: true,
    tableWidth: '800px',
    tableHeight: '400px',
    freezeColumns: 1,
    updateTable:function(instance, cell, col, row, val, label, cellName) {
         if (col == 1) {
             cell.innerHTML = Number.parseFloat(val).toFixed(6);
         }
     }
});

</script>
<script type="text/javascript">
// Make a Download Button
document.getElementById("downloadLC2A1").addEventListener("click", myFunctionDownload);
function myFunctionDownload() {mySpreadsheet2A1.download();};

</script>

<div class="figure" style="text-align: center"><span id="fig:IndonesianLifeTablePlot"></span>
<img src="LifeCon_files/figure-html/IndonesianLifeTablePlot-1.png" alt="Indonesian Life Expectancies. Female life expectancies are given in the red open symbols, males are represented with the blue solid line." width="75%" />
<p class="caption">
Figure 2.16: <strong>Indonesian Life Expectancies.</strong> Female life expectancies are given in the red open symbols, males are represented with the blue solid line.
</p>
</div>
<p><br></p>
<p><strong>On Your Own.</strong> Try a few interactive calculations using <code>R</code>.</p>
<p><br></p>
<div data-datacamp-exercise="" data-height="300" data-encoded="true">
eyJsYW5ndWFnZSI6InIiLCJzYW1wbGUiOiJJbmRMaWZlVGFibGUgPC0gcmVhZC5jc3YoXCJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vT3BlbkFjdFRleHREZXYvTGlmZUNvbi9tYXN0ZXIvRGF0YS9JbmRvbmVzaWFuTGlmZVRhYmxlTm9Gb3JtdWxhLmNzdlwiLCBoZWFkZXIgPSBGKVxuY29sbmFtZXMoSW5kTGlmZVRhYmxlKSA8LSBjKFwiQWdlXCIsXCJGZW1hbGUucXhcIixcIkZlbWFsZS5seFwiLFwiRmVtYWxlLmR4XCIsXCJGZW1hbGUuZXhcIixcIk1hbGUucXhcIixcIk1hbGUubHhcIixcIk1hbGUuZHhcIixcIk1hbGUuZXhcIilcbnN1bW1hcnkoSW5kTGlmZVRhYmxlKVxucGxvdChJbmRMaWZlVGFibGUkQWdlLEluZExpZmVUYWJsZSRGZW1hbGUuZXgsIHhsYWI9XCJBZ2VcIix5bGFiPVwiTGlmZSBFeHBlY3RhbmN5XCIsIGNvbD1cInJlZFwiKVxubGluZXMoSW5kTGlmZVRhYmxlJEFnZSxJbmRMaWZlVGFibGUkTWFsZS5leCwgY29sPVwiYmx1ZVwiKSJ9
</div>

<p><span class="math inline">\(\require{enclose}\)</span> <!-- Later equations only properly knit if this is beforehand once in the code --></p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introduction.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="C-Benefit.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
